# 광물을 통한 분류 예측

## 1. 데이터의 확인 및 실행

In [4]:
import pandas as pd


df = pd.read_csv("/content/sample_data/sonar.csv", header= None)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       208 non-null    float64
 1   1       208 non-null    float64
 2   2       208 non-null    float64
 3   3       208 non-null    float64
 4   4       208 non-null    float64
 5   5       208 non-null    float64
 6   6       208 non-null    float64
 7   7       208 non-null    float64
 8   8       208 non-null    float64
 9   9       208 non-null    float64
 10  10      208 non-null    float64
 11  11      208 non-null    float64
 12  12      208 non-null    float64
 13  13      208 non-null    float64
 14  14      208 non-null    float64
 15  15      208 non-null    float64
 16  16      208 non-null    float64
 17  17      208 non-null    float64
 18  18      208 non-null    float64
 19  19      208 non-null    float64
 20  20      208 non-null    float64
 21  21      208 non-null    float64
 22  22

In [6]:
df.head(5)

0       1       2       3       4   ...      56      57      58      59  60
0  0.0200  0.0371  0.0428  0.0207  0.0954  ...  0.0180  0.0084  0.0090  0.0032   R
1  0.0453  0.0523  0.0843  0.0689  0.1183  ...  0.0140  0.0049  0.0052  0.0044   R
2  0.0262  0.0582  0.1099  0.1083  0.0974  ...  0.0316  0.0164  0.0095  0.0078   R
3  0.0100  0.0171  0.0623  0.0205  0.0205  ...  0.0050  0.0044  0.0040  0.0117   R
4  0.0762  0.0666  0.0481  0.0394  0.0590  ...  0.0072  0.0048  0.0107  0.0094   R

[5 rows x 61 columns]

## 2. 초음파 광물 예측 : 데이터확인 및 실행

### 관련 패키지 임포트 

In [7]:
# 모델, 레이어, 전처리 
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import LabelEncoder

import pandas as pd
import numpy as np
import tensorflow as tf

# seed값 설정
seed = 3
np.random.seed(seed)
tf.random.set_seed(seed)

### 데이터 로그 및 전처리 

In [15]:
df = pd.read_csv("/content/sample_data/sonar.csv", header = None)
dataset = df.values
X = dataset[:, : 60].astype(float)   # ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).
Y_obj = dataset[:, 60]

In [16]:
# 문자열 변환
e = LabelEncoder()
e.fit(Y_obj)
Y = e.transform(Y_obj)

### 모델 설정 및 컴파일 및 실행

In [17]:
# 모델 설정
model = Sequential()
model.add(Dense(24, input_dim=60, activation= 'relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [20]:
# 모델 컴파일
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [21]:
# 모델 실행
model.fit(X, Y, epochs= 200, batch_size = 5)

Epoch 1/200
42/42 [==============================] - 2s 2ms/step - loss: 0.6965 - accuracy: 0.5441
Epoch 2/200
42/42 [==============================] - 0s 2ms/step - loss: 0.6563 - accuracy: 0.6602
Epoch 3/200
42/42 [==============================] - 0s 2ms/step - loss: 0.6181 - accuracy: 0.7103
Epoch 4/200
42/42 [==============================] - 0s 2ms/step - loss: 0.6063 - accuracy: 0.6979
Epoch 5/200
42/42 [==============================] - 0s 2ms/step - loss: 0.5939 - accuracy: 0.6998
Epoch 6/200
42/42 [==============================] - 0s 2ms/step - loss: 0.5499 - accuracy: 0.7335
Epoch 7/200
42/42 [==============================] - 0s 2ms/step - loss: 0.5092 - accuracy: 0.8038
Epoch 8/200
42/42 [==============================] - 0s 2ms/step - loss: 0.4728 - accuracy: 0.8179
Epoch 9/200
42/42 [==============================] - 0s 2ms/step - loss: 0.4954 - accuracy: 0.7867
Epoch 10/200
42/42 [==============================] - 0s 2ms/step - loss: 0.4601 - accuracy: 0.8435
Epoch 11/

In [24]:
# 결과 출력
print("\n Accuracy : %.4f" %(model.evaluate(X, Y))[1])

7/7 [==============================] - 0s 2ms/step - loss: 0.0019 - accuracy: 1.0000

 Accuracy : 1.0000


* 모델의 정확도가 100%가 나온다. 정말 정상적으로 예측을 한것일까? 여기서 테스트셋에 최적화되는 문제인 과적합(overfitting)의 문제가 나온다.

* 과적합을 방지하기 위해서는, 학습을 하는 데이터셋과 이를 테스트 할 데이터셋을 완전 구분한 다음 학습과 동시에 테스트를 병행하며 진행하는 것이 한 방법임.

### 초음과 광물 예측 - 학습셋과 테스트셋 구분

In [25]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [27]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [28]:
# seed값 설정
seed = 0
np.random.seed(seed)
tf.random.set_seed(seed)

In [31]:
# 데이터 로드 
df = pd.read_csv("/content/sample_data/sonar.csv", header = None)
dataset = df.values
X = dataset[:, 0:60].astype(float)
Y_obj = dataset[:, 60]

In [32]:
# LabelEncoder
e = LabelEncoder()
e.fit(Y_obj)
Y = e.transform(Y_obj)

In [34]:
# 학습과 테스트셋 구분
X_train, X_test, Y_train, Y_test  = train_test_split(X, Y, test_size = .3, random_state = seed)

### 모델 설정 및 수행 

In [36]:
model = Sequential()
model.add(Dense(24, input_dim = 60, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [37]:
model.compile(optimizer = 'adam', loss = "mean_squared_error", metrics = ['accuracy'])

In [38]:
model.fit(X_train, Y_train, epochs=130, batch_size = 5)

Epoch 1/130
29/29 [==============================] - 0s 2ms/step - loss: 0.2443 - accuracy: 0.5476
Epoch 2/130
29/29 [==============================] - 0s 1ms/step - loss: 0.2301 - accuracy: 0.6902
Epoch 3/130
29/29 [==============================] - 0s 1ms/step - loss: 0.2192 - accuracy: 0.6978
Epoch 4/130
29/29 [==============================] - 0s 1ms/step - loss: 0.2059 - accuracy: 0.7966
Epoch 5/130
29/29 [==============================] - 0s 2ms/step - loss: 0.2070 - accuracy: 0.7166
Epoch 6/130
29/29 [==============================] - 0s 1ms/step - loss: 0.1933 - accuracy: 0.7483
Epoch 7/130
29/29 [==============================] - 0s 1ms/step - loss: 0.1873 - accuracy: 0.7974
Epoch 8/130
29/29 [==============================] - 0s 1ms/step - loss: 0.1808 - accuracy: 0.7415
Epoch 9/130
29/29 [==============================] - 0s 1ms/step - loss: 0.1765 - accuracy: 0.7701
Epoch 10/130
29/29 [==============================] - 0s 1ms/step - loss: 0.1685 - accuracy: 0.7950
Epoch 11/

### 테스트셋에 모델 적용 

In [40]:
print("\n Test Accuracy : %.4f" %(model.evaluate(X_test, Y_test)[1]))

2/2 [==============================] - 0s 5ms/step - loss: 0.1493 - accuracy: 0.7937

 Test Accuracy : 0.7937


### 예측값 테스트 

In [41]:
test_data = [[0.0260,0.0363,0.0136,0.0272,0.0214,0.0338,0.0655,0.1400,0.1843,0.2354,0.2720,0.2442,0.1665,0.0336,0.1302,0.1708,0.2177,0.3175,0.3714,0.4552,0.5700,0.7397,0.8062,0.8837,0.9432,1.0000,0.9375,0.7603,0.7123,0.8358,0.7622,0.4567,0.1715,0.1549,0.1641,0.1869,0.2655,0.1713,0.0959,0.0768,0.0847,0.2076,0.2505,0.1862,0.1439,0.1470,0.0991,0.0041,0.0154,0.0116,0.0181,0.0146,0.0129,0.0047,0.0039,0.0061,0.0040,0.0036,0.0061,0.0115]]
model.predict_classes(test_data)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([[0]], dtype=int32)

In [42]:
test_data = [[0.0229,0.0369,0.0040,0.0375,0.0455,0.1452,0.2211,0.1188,0.0750,0.1631,0.2709,0.3358,0.4091,0.4400,0.5485,0.7213,0.8137,0.9185,1.0000,0.9418,0.9116,0.9349,0.7484,0.5146,0.4106,0.3443,0.6981,0.8713,0.9013,0.8014,0.4380,0.1319,0.1709,0.2484,0.3044,0.2312,0.1338,0.2056,0.2474,0.2790,0.1610,0.0056,0.0351,0.1148,0.1331,0.0276,0.0763,0.0631,0.0309,0.0240,0.0115,0.0064,0.0022,0.0122,0.0151,0.0056,0.0026,0.0029,0.0104,0.0163]]
model.predict_classes(test_data)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([[0]], dtype=int32)

In [46]:
t3 = [[0.0286,0.0453,0.0277,0.0174,0.0384,0.0990,0.1201,0.1833,0.2105,0.3039,0.2988,0.4250,0.6343,0.8198,1.0000,0.9988,0.9508,0.9025,0.7234,0.5122,0.2074,0.3985,0.5890,0.2872,0.2043,0.5782,0.5389,0.3750,0.3411,0.5067,0.5580,0.4778,0.3299,0.2198,0.1407,0.2856,0.3807,0.4158,0.4054,0.3296,0.2707,0.2650,0.0723,0.1238,0.1192,0.1089,0.0623,0.0494,0.0264,0.0081,0.0104,0.0045,0.0014,0.0038,0.0013,0.0089,0.0057,0.0027,0.0051,0.0062]]
model.predict_classes(t3)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([[1]], dtype=int32)

# 초음파 광물 예측 : 모델 저장과 재사용 

In [47]:
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import LabelEncoder

import pandas as pd
import numpy as np
import tensorflow as tf

#seed값 설정
seed = 0
np.random.seed(seed)
tf.random.set_seed(seed)

In [48]:
df = pd.read_csv("/content/sample_data/sonar.csv", header= None)

In [57]:
# 데이터셋  분리 
dataset = df.values
X = dataset[:, :60].astype(float)
Y_obj = dataset[:, 60]

In [58]:
# LabelEncoder
e = LabelEncoder()
e.fit(Y_obj)
Y = e.transform(Y_obj)

In [59]:
# 학습셋과 테스트셋을 분리 
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = .3, random_state = seed)

In [60]:
# 모델 설정
model = Sequential()
model.add(Dense(24, input_dim = 60, activation='relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [61]:
# 모델 컴파일 및 수행
model.compile(optimizer = 'rmsprop', loss = 'mean_squared_error', metrics = ['accuracy'])

In [62]:
# 모델 수행
model.fit(X_train, Y_train, epochs = 130, batch_size=5)

Epoch 1/130
29/29 [==============================] - 0s 2ms/step - loss: 0.2546 - accuracy: 0.4188
Epoch 2/130
29/29 [==============================] - 0s 2ms/step - loss: 0.2430 - accuracy: 0.5651
Epoch 3/130
29/29 [==============================] - 0s 2ms/step - loss: 0.2343 - accuracy: 0.6921
Epoch 4/130
29/29 [==============================] - 0s 2ms/step - loss: 0.2246 - accuracy: 0.7493
Epoch 5/130
29/29 [==============================] - 0s 2ms/step - loss: 0.2288 - accuracy: 0.6562
Epoch 6/130
29/29 [==============================] - 0s 2ms/step - loss: 0.2146 - accuracy: 0.7418
Epoch 7/130
29/29 [==============================] - 0s 2ms/step - loss: 0.2173 - accuracy: 0.6561
Epoch 8/130
29/29 [==============================] - 0s 2ms/step - loss: 0.2011 - accuracy: 0.7555
Epoch 9/130
29/29 [==============================] - 0s 2ms/step - loss: 0.1993 - accuracy: 0.7493
Epoch 10/130
29/29 [==============================] - 0s 2ms/step - loss: 0.1957 - accuracy: 0.7869
Epoch 11/

In [64]:
# 모델 저장 및 재사용
model.save("my_model.h5")

In [65]:
# 테스트를 위해 메모리 내의 모델 삭제
del model

In [68]:
# 저장한 모델을 불러옴
model = load_model('my_model.h5')

In [69]:
# 불러온 모델로 수행
print("\n Test Accuracy : %.4f" %(model.evaluate(X_test, Y_test)[1]))

2/2 [==============================] - 0s 5ms/step - loss: 0.1352 - accuracy: 0.8571

 Test Accuracy : 0.8571


### 실제값으로 예측 테스트 

In [70]:
test_data = [[0.0229,0.0369,0.0040,0.0375,0.0455,0.1452,0.2211,0.1188,0.0750,0.1631,0.2709,0.3358,0.4091,0.4400,0.5485,0.7213,0.8137,0.9185,1.0000,0.9418,0.9116,0.9349,0.7484,0.5146,0.4106,0.3443,0.6981,0.8713,0.9013,0.8014,0.4380,0.1319,0.1709,0.2484,0.3044,0.2312,0.1338,0.2056,0.2474,0.2790,0.1610,0.0056,0.0351,0.1148,0.1331,0.0276,0.0763,0.0631,0.0309,0.0240,0.0115,0.0064,0.0022,0.0122,0.0151,0.0056,0.0026,0.0029,0.0104,0.0163]]
model.predict_classes(test_data)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([[0]], dtype=int32)

In [71]:
t3 = [[0.0286,0.0453,0.0277,0.0174,0.0384,0.0990,0.1201,0.1833,0.2105,0.3039,0.2988,0.4250,0.6343,0.8198,1.0000,0.9988,0.9508,0.9025,0.7234,0.5122,0.2074,0.3985,0.5890,0.2872,0.2043,0.5782,0.5389,0.3750,0.3411,0.5067,0.5580,0.4778,0.3299,0.2198,0.1407,0.2856,0.3807,0.4158,0.4054,0.3296,0.2707,0.2650,0.0723,0.1238,0.1192,0.1089,0.0623,0.0494,0.0264,0.0081,0.0104,0.0045,0.0014,0.0038,0.0013,0.0089,0.0057,0.0027,0.0051,0.0062]]
model.predict_classes(t3)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([[1]], dtype=int32)

## 초음파 광물 예측 : Stratified KFold검증

In [13]:
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense

# 전처리
from sklearn.preprocessing import LabelEncoder

# K겹교차검증
from sklearn.model_selection import StratifiedKFold

import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
# seed값 설정
seed = 0
np.random.seed(seed)
tf.random.set_seed(seed)

In [3]:
df = pd.read_csv("/content/sample_data/sonar.csv", header = None)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       208 non-null    float64
 1   1       208 non-null    float64
 2   2       208 non-null    float64
 3   3       208 non-null    float64
 4   4       208 non-null    float64
 5   5       208 non-null    float64
 6   6       208 non-null    float64
 7   7       208 non-null    float64
 8   8       208 non-null    float64
 9   9       208 non-null    float64
 10  10      208 non-null    float64
 11  11      208 non-null    float64
 12  12      208 non-null    float64
 13  13      208 non-null    float64
 14  14      208 non-null    float64
 15  15      208 non-null    float64
 16  16      208 non-null    float64
 17  17      208 non-null    float64
 18  18      208 non-null    float64
 19  19      208 non-null    float64
 20  20      208 non-null    float64
 21  21      208 non-null    float64
 22  22

In [6]:
# 데이터셋 로드 
dataset = df.values
X = dataset[:, 0: 60].astype(float)
Y_obj = dataset[:, 60]

In [8]:
# LabelEncoder
e = LabelEncoder()
e.fit(Y_obj)
Y = e.transform(Y_obj)

### K겹 교차검증 및 모델 설정 및 컴파일 수행
* 모델 저장

In [12]:
# 10개의 폴드로 쪼갬
n_folds = 10
skf  = StratifiedKFold(n_splits= n_folds, shuffle=False, random_state=seed)

# train index와 test index를 리턴
model = Sequential()
model.add(Dense(24, input_dim = 60, activation= 'relu'))
model.add(Dense(10, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss = 'mean_squared_error', optimizer = 'adam', metrics = ['accuracy'])

# accuracy리스트 
accuracy = []

for train, test in skf.split(X, Y): 
  model.fit(X[train], Y[train], epochs = 10, batch_size = 5)
  k_accuracy = "%.4f" %(model.evaluate(X[test], Y[test])[1])
  accuracy.append(k_accuracy)

model.save("kfold_model.h5")
# 결과 출력
print("\n %.f fold accuracy : " %n_folds, accuracy)

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


Epoch 1/10
38/38 [==============================] - 0s 2ms/step - loss: 0.2434 - accuracy: 0.5591
Epoch 2/10
38/38 [==============================] - 0s 2ms/step - loss: 0.2375 - accuracy: 0.5544
Epoch 3/10
38/38 [==============================] - 0s 2ms/step - loss: 0.2368 - accuracy: 0.5197
Epoch 4/10
38/38 [==============================] - 0s 2ms/step - loss: 0.2340 - accuracy: 0.5380
Epoch 5/10
38/38 [==============================] - 0s 2ms/step - loss: 0.2260 - accuracy: 0.5619
Epoch 6/10
38/38 [==============================] - 0s 2ms/step - loss: 0.2252 - accuracy: 0.5972
Epoch 7/10
38/38 [==============================] - 0s 2ms/step - loss: 0.2192 - accuracy: 0.6419
Epoch 8/10
38/38 [==============================] - 0s 2ms/step - loss: 0.2071 - accuracy: 0.6867
Epoch 9/10
38/38 [==============================] - 0s 2ms/step - loss: 0.1997 - accuracy: 0.7223
Epoch 10/10
1/1 [==============================] - 0s 82ms/step - loss: 0.2798 - accuracy: 0.5238
Epoch 1/10
38/38 [==

### 모델로드 및 재수행 

In [19]:
# 메모리내의 모델 삭제
del model 

In [18]:
# 저장된 모델 로드 및 재수행
model = load_model("kfold_model.h5")
accuracy = []
for train, test in skf.split(X, Y): 
  k_accuracy = "%.4f" %(model.evaluate(X[test], Y[test])[1])
  accuracy.append(k_accuracy)

print("%.f fold's accuracy : " % n_folds , accuracy)

1/1 [==============================] - 0s 18ms/step - loss: 0.0269 - accuracy: 1.0000
10 fold's accuracy :  ['0.9048', '0.9524', '1.0000', '1.0000', '1.0000', '1.0000', '1.0000', '0.9524', '1.0000', '1.0000']
