## 1차원 배열 만들기
* numpy.ndarray가 리스트와 다른점은 동일한 데이터타입의 값만 올수있다는 점.

In [4]:
import numpy as np

ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(ar, type(ar))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


## 벡터화 연산
* 벡터화 연산은 비교연산과 논리연산을 포함한 모든 종류의 수학연산에 적용됨.

In [5]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

만약, 위의 리스트를 2배하는 연산이 있다면 ,우리는 for..in을 사용해.

In [7]:
result = []
for v in data:
    result.append(v * 2)
print(result)    

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


하지만, 벡터화 연산을 이용한다면...for문 반복없이 이렇게 하면 

In [12]:
x = np.array(data)
print(x * 2)

[ 0  2  4  6  8 10 12 14 16 18]


In [17]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(2 * a + b)
print("\n")
print(a == 2)
print(b > 10)
print((a == 2) & (b > 10))
print((a == 2) & (b > 10))

[12 24 36]


[False  True False]
[False  True  True]
[False  True False]
[False  True False]


## 2차원 배열 만들기

In [20]:
c = np.array([[0, 1, 2], [3, 4, 5]])
c
print(len(c), c.shape)   #행의 갯수와 차원정보를 보여줌.
print('열의 갯수 : {0}'.format(c.shape[1]))

2 (2, 3)
열의 갯수 : 3


### 넘파이를 사용해 행렬만들기
10 20 30 40<br>
50 60 70 80

In [23]:
x = np.array([[10, 20, 30, 40],[50, 60, 70, 80]])
print(x, x.shape)

[[10 20 30 40]
 [50 60 70 80]] (2, 4)


## 3차원 배열 만들기

In [27]:
d = np.array(
        [
            [
                [1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]],
                [[11, 12, 13, 14],
                [15, 16, 17, 18],
                [19, 20, 21, 22]
            ]
        ]
)
len(d), len(d[0]), len(d[0][0])

(2, 3, 4)

## 배열의 차원과 크기 알아내기
* ndim : 배열의 차원
* shape : 배열의 크기 

In [29]:
a = np.array([1, 2, 3])
print(a.ndim, a.shape)

1 (3,)


In [31]:
c = np.array([[0, 1, 2], [3, 4, 5]])

print(c.ndim, c.shape)

2 (2, 3)


## 배열의 인덱싱

In [32]:
a = np.array([0, 1, 2, 3, 4])

In [35]:
print(a[2], a[-1])

2 4


In [38]:
a = np.array([[0, 1, 2], [3, 4, 5]])
print(a)

[[0 1 2]
 [3 4 5]]


#### 첫번째 행의 첫번째 열

In [39]:
print(a[0, 0])

0


#### 첫번째 행의 두번째 열

In [40]:
a[0, 1]

1

#### 마지막행의 마지막 열

In [42]:
a[-1, -1]

5

## 배열 슬라이싱

In [43]:
a = np.array([[0, 1, 2, 3],[4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

#### 첫번째 행 전체

In [44]:
a[0,]

array([0, 1, 2, 3])

#### 두번째 열 전체

In [46]:
a[:, 1]

array([1, 5])

#### 두번째 행의 두번째 열부터 끝까지

In [47]:
a[1, 1:]

array([5, 6, 7])

In [48]:
a[:2, :2]

array([[0, 1],
       [4, 5]])

## 행렬에 대한 기본식 점검

In [50]:
m = np.array([[0, 1, 2, 3, 4],
            [5, 6, 7, 8, 9],
            [10, 11, 12, 13, 14]])
print(m, m.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] (3, 5)


In [54]:
m[1, 2] # 값 7을 인덱싱

7

In [56]:
m[2, 4] # 값 14 인덱싱

14

In [58]:
m[1,1:3]  # array([6, 7])

array([6, 7])

In [62]:
m[1:, 2]  # array([ 7, 12])

array([ 7, 12])

##### 결과는 이렇게 나옴
array([[3, 4],
       [8, 9]])

In [64]:
m[0:2, 3:]  

array([[3, 4],
       [8, 9]])

## 배열 인덱싱

In [69]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True, False, True, False])
print(idx)

[ True False  True False  True False  True False]


#### 짝수만 가져온다.

In [71]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [78]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
print(a)
print(a[:, [True, False, False, True]])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  4]
 [ 5  8]
 [ 9 12]]


연습문제 

In [83]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

다음 행렬에서 3의 배수 찾기

In [85]:
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

4로 나누면 1이 남는 수를 찾아줘.!!

In [86]:
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [95]:
cond_3 = x % 3 == 0
cond_3


cond_4 = x % 3 == 1
cond_4

x[cond_3 | cond_4]

array([ 1,  3,  4,  6,  7,  9, 10, 12, 13, 15, 16, 18, 19])