## 배열의 연산

In [1]:
import numpy as np

### 벡터화 연산

In [2]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

벡터화연산을 사용안한다면 우리는 이렇게 할것이다.

In [3]:
z = np.zeros_like(x)
%timeit 
for i in range(10000):
    z[i] = x[i] + y[i]

In [4]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [5]:
%timeit x + y

13.6 µs ± 4.94 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [6]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [7]:
a == b

array([False,  True, False,  True])

In [8]:
a >= b

array([False,  True,  True,  True])

In [9]:
np.all(a == c)

True

In [10]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

#### 지수함수, 로그함수로 변환

In [11]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [12]:
10 ** a

array([    1,    10,   100,  1000, 10000], dtype=int32)

In [13]:
np.log(a + 1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

## 스칼라와 벡터/행렬의 곱셈

In [14]:
x  = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [16]:
x = np.arange(12).reshape(3, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

## 브로드캐스팅
* 서로 다른 크기의 벡터일지라도 작은 사이즈의 벡터를 큰 사이즈의 벡터 크기에 맞춰서 변환하므로 연산이 가능함.

In [18]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [19]:
y = np.ones_like(x)
y

array([1, 1, 1, 1, 1])

In [20]:
x + y, x + 1

(array([1, 2, 3, 4, 5]), array([1, 2, 3, 4, 5]))

In [21]:
x = np.vstack([range(7)[i:i+3] for i in range(5)])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [23]:
y = np.arange(5)[:, np.newaxis]
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [25]:
x + y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [28]:
y = np.arange(3)
y

array([0, 1, 2])

In [32]:
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [34]:
x + y

array([[0, 2, 4],
       [1, 3, 5],
       [2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

## 차원 축소 연산
* 최대/최소 : min, max, argmin, argmax
* 통계 : sum, mean, median, std, var
* 불리언 : all, any

In [35]:
x  = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [37]:
np.sum(x)

10

In [39]:
x = np.array([1, 3, 2])
x.min()

1

In [41]:
x.max()

3

In [43]:
x.argmin()   # 최소값의 위치를 반환

0

In [45]:
x.argmax()    # 최대값의 위치를 반환

1

In [47]:
x = np.array([1, 2, 3, 1])

In [48]:
x.mean()

1.75

In [49]:
np.median(x)

1.5

In [51]:
np.all([True, True, False])

False

In [55]:
np.any([True, True, False, True])

True

In [57]:
a = np.zeros((100, 100), dtype=np.int)
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [58]:
np.any(a != 0)

False

In [59]:
np.all(a == 0)

True

In [60]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

In [61]:
# 벡터 각각의 모든 원소가 True이면 True를 리턴
((a <= b) & ( b <= c)).all()

True

In [68]:
x = np.array([[1, 1], [2, 2]])
x, x.shape

(array([[1, 1],
        [2, 2]]),
 (2, 2))

In [64]:
x.sum()

6

In [66]:
x.sum(axis = 1)  # 행 합계

array([2, 4])

In [67]:
x.sum(axis = 0)  # 열합계

array([3, 3])

#### 연습문제 3.3.1

In [75]:
x1 = np.arange(30, dtype='float').reshape(5, 6)

In [77]:
x1

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29.]])

In [78]:
x1.max()

29.0

#### 각 행의 합

In [80]:
x1.sum(axis = 1)

array([ 15.,  51.,  87., 123., 159.])

#### 각 행의 최대값

In [82]:
x1.max(axis = 1)

array([ 5., 11., 17., 23., 29.])

#### 각 열의 평균

In [84]:
x1.mean(axis = 0)

array([12., 13., 14., 15., 16., 17.])

#### 각 열의 최소값

In [86]:
x1.min(axis = 0)

array([0., 1., 2., 3., 4., 5.])

## 정렬

In [95]:
a = np.array([[4, 3, 5, 7],
             [1, 12, 11, 9],
             [2, 15, 1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [92]:
np.sort(a)  # # axis=-1 또는 axis=1 과 동일

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [98]:
a = np.array([[4, 3, 5, 7],
             [1, 12, 11, 9],
             [2, 15, 1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [99]:
np.sort(a, axis = 0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

#### 만약,자료를 정렬하는 것이 아닌, 순서만 알고 싶다면..

In [103]:
a = np.array([42, 38, 12, 25])
a
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [104]:
all(j)

False

In [105]:
np.sort(a)

array([12, 25, 38, 42])

#### 연습문제 3.3.2

다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은 배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬하라.

In [111]:
a = np.array([[  1,    2,    3,    4],
       [ 46,   99,  100,   71],
       [ 81,   59,   90,  100]])
print(a.shape)
print(a)

(3, 4)
[[  1   2   3   4]
 [ 46  99 100  71]
 [ 81  59  90 100]]
