### 넘파이 ndarray개념

import numpy as np

In [ ]:
array1 = np.array([1, 2, 3])
print('array1 type : ' , type(array1))  # R에서는 typeof
print('array1 shape : ' , array1.shape)  # R의 Dim

array2 = np.array([[1, 2, 3],
                   [2, 3, 4]])
print('array2 type : ', type(array2))
print('arra2 shape : ', array2.shape)  # 2행 3열

array3 = np.array([[1, 2, 3]])

print('array3 type : ', type(array3)) 
print('array3 shape : ', array3.shape) #1행 3열

#### ndim을 이용해 array차원 알아보기 

print('array1 : {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

#### ndarray 데이터 타입
- 같은 데이터 타입만 가능
- dtype속성으로 확인 가능

In [ ]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)

print(type(array1))
print(array1, array1.dtype)

- 만약 int형과 str형의 데이터 섞여 있는 리스트타입의 데이터를 ndarray으로 변경하면?

In [20]:
list2 = [1, 2, 'test']

array2 = np.array(list2)

print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)

print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


결과에서 보는 바와 같이 크기가 더 큰 타입으로 변환된다.
 - 숫자는 더 큰 문자형으로 같은 숫자형이면 더 큰 실수형으로 변경됨을 알 수 있다.

#### astype을 이용한 데이터 타입 변경

In [ ]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

float_num = [1.1, 2.1, 3.1]
array_float1 = np.array(float_num)
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

### ndarray를 편리하게 생성 - arrange, zeros, ones

In [27]:
sequence_array = np.arange(10) # 0 ~ 9까지의 수.
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [31]:
zero_array = np.zeros((3, 2), dtype='int32')  # zero vector
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3, 2)) # one-vector
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


#### reshape

In [37]:
array1 = np.arange(10)
print('array1 : \n', array1)

array2 = array1.reshape(2, 5)  # 2행 5열로 바꿈
print('array2 :\n', array2)

array3 = array1.reshape(5,2)
print('array3 : \n', array3)

array1 : 
 [0 1 2 3 4 5 6 7 8 9]
array2 :
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [38]:
array1.reshape(4, 3) # 변경이 불가능한 shape

ValueError: cannot reshape array of size 10 into shape (4,3)

In [40]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1, 5)  # 열은 5개로 정해졌으니 인터프리터가 알아서 행은 계산해서 만들어줘
print('array2 shape :', array2.shape)

array3 = array1.reshape(5, -1)
print('array3 shape : ', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape : (2, 5)
array3 shape :  (5, 2)


In [41]:
array1 = np.arange(10)
array4 = array1.reshape(-1, 4)

ValueError: cannot reshape array of size 10 into shape (4)

In [45]:
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d:\n', array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1)
print('array5 shape : ', array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print('array6: \n', array6.tolist())
print('array6 shape : ', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5 shape :  (8, 1)
array6: 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape :  (8, 1)


#### 인덱싱(indexing)
- 단일값 추출

In [49]:
# 1부터 9까지의 1차원 ndarray생성 
array1 = np.arange(start = 1, stop = 10)
print('array1 : ', array1)

# index는 0부터 시작하므로 array1[2]는 3번째 인덱스 위치의 데이터 값을 의미
value = array1[2]
print('value : ', value)
print(type(value))

array1 :  [1 2 3 4 5 6 7 8 9]
value :  3
<class 'numpy.int32'>


In [51]:
print('맨 뒤의 값 : ', array1[-1], '맨 뒤에서 두번째 값 : ', array1[-2])

맨 뒤의 값 :  9 맨 뒤에서 두번째 값 :  8


In [53]:
array1[0] = 9
array1[8] = 0
print('array1 : ', array1)

array1 :  [9 2 3 4 5 6 7 8 0]


In [59]:
array1d = np.arange(start = 1, stop = 10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('(row = 0, col = 0) index 가리키는 값 : ', array2d[0, 0])
print('(row = 0, col = 1) index 가리키는 값 : ', array2d[0, 1])
print('(row = 1, col = 0) index 가리키는 값 : ', array2d[1, 0])
print('(row = 2, col = 2) index 가리키는 값 : ', array2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row = 0, col = 0) index 가리키는 값 :  1
(row = 0, col = 1) index 가리키는 값 :  2
(row = 1, col = 0) index 가리키는 값 :  4
(row = 2, col = 2) index 가리키는 값 :  9


#### slicing

In [62]:
array1 = np.arange(start = 1, stop = 10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [65]:
array1 = np.arange(start = 1, stop = 10)
array4 = array1[:3] # 0인덱스부터 2번 인덱스까지 추출 
print(array4)

array5 = array1[3:] # 3번 인덱스부터 끝까지.
print(array5)

array6 = array1[:]  #처음부터 9번 인덱스까지.
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [73]:
array1d = np.arange(start =1 , stop = 10)
array2d = array1d.reshape(3, 3)
print('array2d : \n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n ', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
  [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]
