### 넘파이 ndarray개념
* ndarray생성 - np.array()

In [2]:
import numpy as np

In [3]:
list1 = [1, 2, 3]
print("list1:",list1)
print("list1 type:",type(list1))  # R에서는 typeof

array1 = np.array(list1)
print("array1:",array1)
print("array1 type:", type(array1))

list1: [1, 2, 3]
list1 type: <class 'list'>
array1: [1 2 3]
array1 type: <class 'numpy.ndarray'>


* ndarray 의 형태(shape)와 차원

In [5]:
array1 = np.array([1, 2, 3])
print('array1 type : ' , type(array1))  # R에서는 typeof
print('array1 shape : ' , array1.shape)  # R의 Dim

array1 type :  <class 'numpy.ndarray'>
array1 shape :  (3,)


In [7]:
array2 = np.array([[1, 2, 3],
                   [2, 3, 4]])
print('array2 type : ', type(array2))
print('arra2 shape : ', array2.shape)  # 2행 3열


array2 type :  <class 'numpy.ndarray'>
arra2 shape :  (2, 3)


In [8]:
array3 = np.array([[1, 2, 3]])  # 내포된 리스트 

print('array3 type : ', type(array3)) 
print('array3 shape : ', array3.shape) #1행 3열

array3 type :  <class 'numpy.ndarray'>
array3 shape :  (1, 3)


#### ndim을 이용해 array차원 알아보기 

In [9]:
print('array1 : {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1 : 1차원, array2: 2차원, array3:  2차원


#### ndarray 데이터 값 타입
- 같은 데이터 타입만 가능
- dtype속성으로 확인 가능

In [10]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)

print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


- 만약 int형과 str형의 데이터 섞여 있는 리스트타입의 데이터를 ndarray으로 변경하면?

In [14]:
# 정수형타입이 문자형의 바뀜
list2 = [1, 2, 'test']

array2 = np.array(list2)

print(array2, array2.dtype)

['1' '2' 'test'] <U11


In [13]:
# 정수형값이 실수형으로 변환이 됨
list3 = [1, 2, 3.0]
array3 = np.array(list3)

print(array3, array3.dtype)

[1. 2. 3.] float64


결과에서 보는 바와 같이 크기가 더 큰 타입으로 변환된다.
 - 숫자는 더 큰 문자형으로 같은 숫자형이면 더 큰 실수형으로 변경됨을 알 수 있다.

#### astype을 이용한 데이터 타입 변경

In [15]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')  # 64비트형 실수형으로 형변환
print(array_float, array_float.dtype)

[1. 2. 3.] float64


In [18]:
array_int1 = array_float.astype('int32')  # 32비트 정수형으로 형변환
print(array_int1, array_int1.dtype)

[1 2 3] int32


In [17]:
float_num = [1.1, 2.1, 3.1]
array_float1 = np.array(float_num)
array_int2 = array_float1.astype('int32')  # 32비트형 정수형
print(array_int2, array_int2.dtype)

[1 2 3] int32


* **ndarray에서 axis기반의 연산함수 수행**

In [19]:
array2 = np.array([[1, 2, 3], [2, 3, 4]])
print(array2.sum())  # 아무것도 없으면 전체를 다 더함.
print(array2.sum(axis=0))  # 행방향
print(array2.sum(axis=1))  # 열방향

15
[3 5 7]
[6 9]


* **ndarray를 편리하게 생성 - arrange, zeros, ones**
- 특정크기와 차원을 가진 ndaaray를 연속값이나 0또는 1로 초기화 생성해야 할 경우 사용(주로 테스트용으로 데이터를 만들거나 대규모의 데이터를 일괄적으로 초기화해야 할 경우 사용)

In [20]:
sequence_array = np.arange(10) # 0 ~ 9까지의 수.
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [22]:
zero_array = np.zeros((3, 2), dtype='int32')  # zero vector
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [23]:
one_array = np.ones((3, 2)) # one-vector, dtype이 명시가 안되어있으면 기본이 실수형이다.
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


#### reshape
- ndarray의 차원과 크기를 변경하는 reshape()
- 변환 형태를 함수 인자로 부여

In [24]:
array1 = np.arange(10)
print('array1 : \n', array1)

array1 : 
 [0 1 2 3 4 5 6 7 8 9]


In [25]:
# 2차원
array2 = array1.reshape(2, 5)  # 2행 5열로 바꿈
print('array2 :\n', array2)

array2 :
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [26]:
array3 = array1.reshape(5,2)
print('array3 : \n', array3)

array3 : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [27]:
# 변경이 불가능한 shape구조를 입력하면 오류 발생
array1.reshape(4, 3)  # 10개의 원소를 가지고있는데...4*3으로 변환하래.

ValueError: cannot reshape array of size 10 into shape (4,3)

**reshape()에 -1 인자값을 부여하여 특정 차원으로 고정된 가변적인 ndarray형태 변환**
- reshape(-1, 5)와 같이 인자에 -1을 부여하면 -1에 해당하는 axis의 크기는 가변적이되 -1이 아닌 인자값(여기서는 5)에 해당하는 axis크기는 인자값으로 고정하여 ndarray의 shape를 변환
- reshape()는 reshape(-1, 1), reshape(-1,)과 같은 형식으로 변환이 요구되는 경우가 많습니다.
주로 머신러닝 API의 인자로 1차원 ndarray을 명확하게 2차원 ndarray로 변환하여 입력하기를 원하거나 , 또는 반대의 경우가 있을 경우 reshape()를 이용하여 ndarray의 형태를 변환시켜 주는데 사용.
- reshape(-1,) --> 1차원으로 변환
- reshape(-1, 1) --> 2차원으로 변환하되 컬럼 axis크기가 1로 고정.

In [28]:
array1 = np.arange(10)
print(array1)
print(array1.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [29]:
#컬럼 axis 크기는 5에 고정하고 로우 axis크기를 이에 맞춰 자동으로 변환. 즉 2x5 형태로 변환 
array2 = array1.reshape(-1,5)
print('array2 shape:',array2.shape)
print('array2:\n', array2)

array2 shape: (2, 5)
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [30]:
#로우 axis 크기는 5로 고정하고 컬럼 axis크기는 이에 맞춰 자동으로 변환. 즉 5x2 형태로 변환 
array3 = array1.reshape(5, -1) 
print('array3 shape : ', array3.shape)
display(array3)

array3 shape :  (5, 2)


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [32]:
# reshape()는 (-1, 1), (-1, )와 같은 형태로 주로 사용
# 1차원 ndarray를 2차원으로 또는 2차원 ndarray를 1차원으로 변환 시 사용
array1 = np.arange(5)

# 1차원 ndarray를 2차원으로 변환하되, 컬럼 axis크기는 반드시 1이여야 함.
array2d_1 = array1.reshape(-1, 1)
print("array2d_1 shape : ", array2d_1.shape)
print("array2d_1 \n : ", array2d_1)

array2d_1 shape :  (5, 1)
array2d_1 
 :  [[0]
 [1]
 [2]
 [3]
 [4]]


In [33]:
# 2차원 ndarray를 1차원으로 변환
array1d = array2d_1.reshape(-1,)
print("array1d shape : ", array1d.shape)
print("array1d \n : ", array1d)

array1d shape :  (5,)
array1d 
 :  [0 1 2 3 4]


In [34]:
# -1을 적용하여도 변환이 불가능한 형태로의 변환을 요구할 경우 오류 발생
array1 = np.arange(10)

try:
    array4 = array1.reshape(-1, 4)   # ValueError: cannot reshape array of size 10 into shape (4)
except ValueError as e:
    pass
finally:
    array4 = array1.reshape(-1, 5)  # 변환가능하여 오류 안남
    display(array4)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [36]:
# 반드시 -1값은 1개의 인자만 입력해야 함
array1 = np.arange(10)
array4 = array1.reshape(-1, 4)  # ValueError: cannot reshape array of size 10 into shape (4)

ValueError: cannot reshape array of size 10 into shape (4)

In [39]:
# 반드시 -1 값은 1개의 인자만 입력해야 함.
# ValueError: can only specify one unknown dimension
array1.reshape(-1, -1)

ValueError: can only specify one unknown dimension

In [38]:
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d:\n', array3d.tolist())

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


In [33]:
# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1)
print('array5 shape : ', array5.shape)

array5 shape :  (8, 1)


In [34]:
# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print('array6: \n', array6.tolist())
print('array6 shape : ', array6.shape)

array6: 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape :  (8, 1)


#### 인덱싱(indexing)
- 단일값 추출

In [40]:
# 1부터 9까지의 1차원 ndarray생성 
array1 = np.arange(start = 1, stop = 10)  # R에서는 range가 있음
print('array1 : ', array1)

# index는 0부터 시작하므로 array1[2]는 3번째 인덱스 위치의 데이터 값을 의미
value = array1[2]
print('value : ', value)
print(type(value))

array1 :  [1 2 3 4 5 6 7 8 9]
value :  3
<class 'numpy.int32'>


In [41]:
print('맨 뒤의 값 : ', array1[-1], '맨 뒤에서 두번째 값 : ', array1[-2])

맨 뒤의 값 :  9 맨 뒤에서 두번째 값 :  8


In [42]:
array1[0] = 9
array1[8] = 0
print('array1 : ', array1)

array1 :  [9 2 3 4 5 6 7 8 0]


In [45]:
array1d = np.arange(start = 1, stop = 10)
array2d = array1d.reshape(3, 3)

print(array2d)

print('(row = 0, col = 0) index 가리키는 값 : ', array2d[0, 0])
print('(row = 0, col = 1) index 가리키는 값 : ', array2d[0, 1])
print('(row = 1, col = 0) index 가리키는 값 : ', array2d[1, 0])
print('(row = 2, col = 2) index 가리키는 값 : ', array2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row = 0, col = 0) index 가리키는 값 :  1
(row = 0, col = 1) index 가리키는 값 :  2
(row = 1, col = 0) index 가리키는 값 :  4
(row = 2, col = 2) index 가리키는 값 :  9


#### slicing
* `:` 기호 사이에 시작 인덱스와 종료 인덱스를 표시.시작 인덱스에서 종료 인덱스-1 위치에 있는 ndarray를 반환

In [47]:
array1 = np.arange(start = 1, stop = 10)
array3 = array1[0:3]
print("array1 : ", array1)
print(array3)
print(type(array3))

array1 :  [1 2 3 4 5 6 7 8 9]
[1 2 3]
<class 'numpy.ndarray'>


In [48]:
array1 = np.arange(start = 1, stop = 10)
array4 = array1[:3] # 0인덱스부터 2번 인덱스까지 추출 
print(array4)

array5 = array1[3:] # 3번 인덱스부터 끝까지.
print(array5)

array6 = array1[:]  #처음부터 9번 인덱스까지.
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [51]:
array1d = np.arange(start =1 , stop = 10)
array2d = array1d.reshape(3, 3)
print('array2d : \n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n ', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
  [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [52]:
print(array2d[0])  # 1차원 ndarray반환
print(array2d[1])
print('array2d[0] shape :', array2d[0].shape, 'array2d[1] shape : ', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape : (3,) array2d[1] shape :  (3,)


#### 팬시 인덱싱
- 리스트나 ndarray로 인덱스 집합을 지정하면 해당위치의 인덱스에 해당하는 ndaaray를 반환하는 인덱싱 방식

In [54]:
array1d = np.arange(start = 1, stop = 10)
array2d = array1d.reshape(3, 3)

print('array2d : ', array2d)

array2d :  [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [56]:
array3 = array2d[[0, 1], 2]
print('array2d[[0, 1], 2] => ', array3.tolist())  # 리스트로 변환

array2d[[0, 1], 2] =>  [3, 6]


In [57]:
array4 = array2d[[0, 1], 0:2]
print('array2d[[0, 1], 0:2] => ', array4.tolist())

array2d[[0, 1], 0:2] =>  [[1, 2], [4, 5]]


In [58]:
array5 = array2d[[0, 1]]
print('array2d[[0, 1]] =>', array5.tolist())

array2d[[0, 1]] => [[1, 2, 3], [4, 5, 6]]


#### boolean indexing
- 조건 필터링과 검색을 동시에 할수 있음.

In [60]:
array1d = np.arange(start = 1, stop = 10)
# []안에 array1d > 5 Boolean Indexing을 적용
print(array1d)

[1 2 3 4 5 6 7 8 9]


In [68]:
print(array1d > 5 )
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값  :', array3)

[False False False False False  True  True  True  True]
array1d > 5 불린 인덱싱 결과 값  : [6 7 8 9]


In [65]:
# 5보다 큰 것이 위치하는 원소는 True, 아니면 False
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [64]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


즉, 다음과 같이 직접 인덱스 집합을 만들어 대입한 것과 동일한 결과.

In [66]:
indexes = np.array([5, 6, 7, 8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 :', array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


In [69]:
# 불린 인덱싱을 사용하지 않는 경우 구현
array1d  =np.arange(start = 1, stop = 10)
target = []

for i in range(0, 9):
    if array1d[i] > 5:
        target.append(array1d[i])
array_selected = np.array(target)
print(array_selected)

[6 7 8 9]


In [70]:
print(array1d[array1d > 5])

[6 7 8 9]


### 행렬의 정렬 - sort()와 argsort()
- 행렬정렬 : 모두 기본적으로 오름차순으로 행렬 내 원소를 정렬
  - np.sort() : 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환
  - ndarray.sort() : 원 행렬 자체를 정렬한 형태로 변환하며 반환 값은 None
- 정렬된 행렬의 인덱스 반환 : argsort()  - 원본 행렬 정렬 시 정렬된 행렬의 원래 인덱스를 필요로 할 때 np.argsort()를 이용.
  np.argsort()는 정렬 행열의 원본 행렬 인덱스를 ndarray형으로 반환.

#### 행렬 정렬
- np.sort() 나 ndarray.sort() 둘 다 기본적으로 올림차순 소팅

#### ndarray.sort()

In [72]:
org_array = np.array([3, 1, 9, 5])
print('원본 행렬 :', org_array)

원본 행렬 : [3 1 9 5]


In [74]:
#np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출후 반환된 정렬 행렬 : ', sort_array1)
print('소팅 이후 원본 행렬 : ', org_array)

np.sort() 호출후 반환된 정렬 행렬 :  [1 3 5 9]
소팅 이후 원본 행렬 :  [3 1 9 5]


In [76]:
# ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출후 반환된 행렬 : ', sort_array2)   # 원본행렬을 정렬하므로 None를 리턴
print('org_array.sort() 호출후 원본 행렬 : ', org_array)  # 원본행렬이 정렬됨

org_array.sort() 호출후 반환된 행렬 :  None
org_array.sort() 호출후 원본 행렬 :  [1 3 5 9]


##### np.sort()

In [78]:
# 내림차순 소팅
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬 : ', sort_array1_desc)

내림차순으로 정렬 :  [9 5 3 1]


In [82]:
array2d = np.array([[8, 12], [7, 1]])
print("정렬전 array2d : \n", array2d)

정렬전 array2d : 
 [[ 8 12]
 [ 7  1]]


In [84]:
sort_array2d_axis0 = np.sort(array2d, axis = 0)
print('로우 방향으로 정렬: \n', sort_array2d_axis0)

로우 방향으로 정렬: 
 [[ 7  1]
 [ 8 12]]


In [85]:
sort_array2d_axis1 = np.sort(array2d, axis = 1)
print('열 방향으로 정렬 : \n', sort_array2d_axis1)

열 방향으로 정렬 : 
 [[ 8 12]
 [ 1  7]]


#### 정렬된 행렬의 인덱스를 반환(argsort())
- 원본행렬이 정렬되었을 때 원본 행렬의 원소에 대한 인덱스를 필요로 할때 np.argsort()를 이용.

np.argsort()를 이용해 원본 행렬의 정렬시 행렬 인덱스 값 구하기 

In [86]:
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬시 원본 행렬의 인덱스 : ', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬시 원본 행렬의 인덱스 :  [1 0 3 2]


In [89]:
org_array = np.array([3, 1, 9, 5])
print(np.sort(org_array)[::-1])   # 내림차순 정렬

sort_indices_desc = np.argsort(org_array)[::-1]
print("행렬 내림차순 정렬 시 원본 행렬의 인덱스 : ", sort_indices_desc)

[9 5 3 1]
행렬 내림차순 정렬 시 원본 행렬의 인덱스 :  [2 3 0 1]


**key-value 형태의 데이터를 John=78, Mike=95, Sarah=84, Kate=98, Samuel=88을 ndarray로 만들고 argsort()를 이용하여 key값을 정렬**

In [96]:
name_array=np.array(['John', 'Mike','Sarah', 'Kate', 'Samuel'])
display(name_array)
score_array = np.array([78, 95, 84, 98, 88])

# score_array의 정렬된 값에 해당하는 원본 행렬 위치 인덱스 반환하고 이를 이용하여 name_array에서 name값 추출
sort_indices = np.argsort(score_array) 
print("sort indices : ", sort_indices) 

name_array_sort = name_array[sort_indices] # 원래 정렬전의 인덱스에 해당하는 이름순으로 
display(name_array_sort)

score_array_sort = score_array[sort_indices]
print(name_array_sort)
print(score_array_sort)

array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'], dtype='<U6')

sort indices :  [0 2 4 1 3]


array(['John', 'Sarah', 'Samuel', 'Mike', 'Kate'], dtype='<U6')

['John' 'Sarah' 'Samuel' 'Mike' 'Kate']
[78 84 88 95 98]


#### 열정렬(왼쪽에서 오른쪽으로 )

In [107]:
arr2d = np.array([[5, 6, 7, 8],[4, 3, 2, 1],[10, 9 , 12, 11]])
print(arr2d.shape)
print('\n')
print(arr2d)

(3, 4)


[[ 5  6  7  8]
 [ 4  3  2  1]
 [10  9 12 11]]


In [108]:
# argsort()한 정렬의 결과에 인덱스를 수행한 것.
# axis의 디폴트값은 axis = -1
arr2d_indices = arr2d.argsort()
print("\n")
print(arr2d_indices)  # 정렬된 행렬의 각 원소 인덱스를 반환



[[0 1 2 3]
 [3 2 1 0]
 [1 0 3 2]]


In [109]:
arr2d.sort(axis = 1)
arr2d

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

#### 행정렬

In [110]:
arr2d = np.array([[5, 6, 7, 8],[4, 3, 2, 1],[10, 9 , 12, 11]])
print('정렬전 : \n', arr2d)
arr2d.sort(axis = 0)
arr2d
print('정렬후 : ', arr2d)

정렬전 : 
 [[ 5  6  7  8]
 [ 4  3  2  1]
 [10  9 12 11]]
정렬후 :  [[ 4  3  2  1]
 [ 5  6  7  8]
 [10  9 12 11]]


In [37]:
arr2d.argsort(axis = 0)

array([[1, 1, 1, 1],
       [0, 0, 0, 0],
       [2, 2, 2, 2]], dtype=int64)

In [103]:
# 내림차순으로 정렬시에 원본 행렬의 인덱스를 구하는것도 np.argsort()[::-1]
org_array = np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스 : ',sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스 :  [2 3 0 1]


### 선형대수 연산 - 행렬 내적과 전치 행렬 구하기 
- 행렬 내적 : 오른쪽 행렬의 행 갯수와 왼쪽 행렬의 열갯수가 동일해야 dot product가 에러가 안남

In [104]:
A = np.array([[1, 2, 3],
             [4, 5, 6]])
B = np.array([[7,8],
            [9, 10],
             [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 곱 \n: ', dot_product)

행렬 내적 곱 
:  [[ 58  64]
 [139 154]]


- 전치 행렬 : 원 행렬에서 행과 열 위치를 교환한 원소로 구성된 행렬을 그 행렬의 전치 행렬이라고 함.

In [105]:
A = np.array([[1, 2],
              [3, 4]])
              
transpose_mat = np.transpose(A)
print('A의 전치행렬 : \n', transpose_mat)              

A의 전치행렬 : 
 [[1 3]
 [2 4]]
