### 넘파이 ndarray개념

In [2]:
import numpy as np

In [ ]:
array1 = np.array([1, 2, 3])
print('array1 type : ' , type(array1))  # R에서는 typeof
print('array1 shape : ' , array1.shape)  # R의 Dim

array2 = np.array([[1, 2, 3],
                   [2, 3, 4]])
print('array2 type : ', type(array2))
print('arra2 shape : ', array2.shape)  # 2행 3열

array3 = np.array([[1, 2, 3]])

print('array3 type : ', type(array3)) 
print('array3 shape : ', array3.shape) #1행 3열

#### ndim을 이용해 array차원 알아보기 

print('array1 : {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

#### ndarray 데이터 타입
- 같은 데이터 타입만 가능
- dtype속성으로 확인 가능

In [3]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)

print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


- 만약 int형과 str형의 데이터 섞여 있는 리스트타입의 데이터를 ndarray으로 변경하면?

In [4]:
list2 = [1, 2, 'test']

array2 = np.array(list2)

print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)

print(array3, array3.dtype)

['1' '2' 'test'] <U11
[1. 2. 3.] float64


결과에서 보는 바와 같이 크기가 더 큰 타입으로 변환된다.
 - 숫자는 더 큰 문자형으로 같은 숫자형이면 더 큰 실수형으로 변경됨을 알 수 있다.

#### astype을 이용한 데이터 타입 변경

In [5]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

float_num = [1.1, 2.1, 3.1]
array_float1 = np.array(float_num)
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### ndarray를 편리하게 생성 - arrange, zeros, ones

In [27]:
sequence_array = np.arange(10) # 0 ~ 9까지의 수.
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [31]:
zero_array = np.zeros((3, 2), dtype='int32')  # zero vector
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3, 2)) # one-vector
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


#### reshape

In [37]:
array1 = np.arange(10)
print('array1 : \n', array1)

array2 = array1.reshape(2, 5)  # 2행 5열로 바꿈
print('array2 :\n', array2)

array3 = array1.reshape(5,2)
print('array3 : \n', array3)

array1 : 
 [0 1 2 3 4 5 6 7 8 9]
array2 :
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3 : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [38]:
array1.reshape(4, 3) # 변경이 불가능한 shape

ValueError: cannot reshape array of size 10 into shape (4,3)

In [40]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1, 5)  # 열은 5개로 정해졌으니 인터프리터가 알아서 행은 계산해서 만들어줘
print('array2 shape :', array2.shape)

array3 = array1.reshape(5, -1)
print('array3 shape : ', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape : (2, 5)
array3 shape :  (5, 2)


In [41]:
array1 = np.arange(10)
array4 = array1.reshape(-1, 4)

ValueError: cannot reshape array of size 10 into shape (4)

In [6]:
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d:\n', array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1)
print('array5 shape : ', array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print('array6: \n', array6.tolist())
print('array6 shape : ', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5 shape :  (8, 1)
array6: 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape :  (8, 1)


#### 인덱싱(indexing)
- 단일값 추출

In [49]:
# 1부터 9까지의 1차원 ndarray생성 
array1 = np.arange(start = 1, stop = 10)
print('array1 : ', array1)

# index는 0부터 시작하므로 array1[2]는 3번째 인덱스 위치의 데이터 값을 의미
value = array1[2]
print('value : ', value)
print(type(value))

array1 :  [1 2 3 4 5 6 7 8 9]
value :  3
<class 'numpy.int32'>


In [51]:
print('맨 뒤의 값 : ', array1[-1], '맨 뒤에서 두번째 값 : ', array1[-2])

맨 뒤의 값 :  9 맨 뒤에서 두번째 값 :  8


In [7]:
array1[0] = 9
array1[8] = 0
print('array1 : ', array1)

IndexError: index 8 is out of bounds for axis 0 with size 8

In [8]:
array1d = np.arange(start = 1, stop = 10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('(row = 0, col = 0) index 가리키는 값 : ', array2d[0, 0])
print('(row = 0, col = 1) index 가리키는 값 : ', array2d[0, 1])
print('(row = 1, col = 0) index 가리키는 값 : ', array2d[1, 0])
print('(row = 2, col = 2) index 가리키는 값 : ', array2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row = 0, col = 0) index 가리키는 값 :  1
(row = 0, col = 1) index 가리키는 값 :  2
(row = 1, col = 0) index 가리키는 값 :  4
(row = 2, col = 2) index 가리키는 값 :  9


#### slicing

In [9]:
array1 = np.arange(start = 1, stop = 10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [10]:
array1 = np.arange(start = 1, stop = 10)
array4 = array1[:3] # 0인덱스부터 2번 인덱스까지 추출 
print(array4)

array5 = array1[3:] # 3번 인덱스부터 끝까지.
print(array5)

array6 = array1[:]  #처음부터 9번 인덱스까지.
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [11]:
array1d = np.arange(start =1 , stop = 10)
array2d = array1d.reshape(3, 3)
print('array2d : \n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n ', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
  [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [14]:
print(array2d[0])  # 1차원 ndarray반환
print(array2d[1])
print('array2d[0] shape :', array2d[0].shape, 'array2d[1] shape : ', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape : (3,) array2d[1] shape :  (3,)


#### 팬시 인덱싱
- 리스트나 ndarray로 인덱스 집합을 지정하면 해당위치의 인덱스에 해당하는 ndaaray를 반환하는 인덱싱 방식

In [21]:
array1d = np.arange(start = 1, stop = 10)
array2d = array1d.reshape(3, 3)

print('array2d : ', array2d)
array3 = array2d[[0, 1], 2]
print('array2d[[0, 1], 2] => ', array3.tolist())

array4 = array2d[[0, 1], 0:2]
print('array2d[[0, 1], 0:2] => ', array4.tolist())

array5 = array2d[[0, 1]]
print('array2d[[0, 1]] =>', array5.tolist())

array2d :  [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[[0, 1], 2] =>  [3, 6]
array2d[[0, 1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0, 1]] => [[1, 2, 3], [4, 5, 6]]


#### boolean indexing
- 조건 필터링과 검색을 동시에 할수 있음.

In [22]:
array1d = np.arange(start = 1, stop = 10)
# []안에 array1d > 5 Boolean Indexing을 적용

array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값  :', array3)

array1d > 5 불린 인덱싱 결과 값  : [6 7 8 9]


In [23]:
# 5보다 큰 것이 위치하는 원소는 True, 아니면 False
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [24]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


즉, 다음과 같이 직접 인덱스 집합을 만들어 대입한 것과 동일한 결과.

In [25]:
indexes = np.array([5, 6, 7, 8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과 :', array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


### 행렬의 정렬 - sort()와 argsort()
- 행렬정렬 : np.sort(), ndarray.sort()
- 정렬된 행렬의 인덱스 반환 : argsort()

#### 행렬 정렬
- np.sort() 나 ndarray.sort() 둘 다 기본적으로 올림차순 소팅

In [30]:
org_array = np.array([3, 1, 9, 5])
print('원본 행렬 :', org_array)

#np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출후 반환된 정렬 행렬 : ', sort_array1)
print('소팅 이후 원본 행렬 : ', org_array)

# ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출후 반환된 행렬 : ', sort_array2)
print('org_array.sort() 호출후 원본 행렬 : ', org_array)

원본 행렬 : [3 1 9 5]
np.sort() 호출후 반환된 정렬 행렬 :  [1 3 5 9]
소팅 이후 원본 행렬 :  [3 1 9 5]
org_array.sort() 호출후 반환된 행렬 :  None
org_array.sort() 호출후 원본 행렬 :  [1 3 5 9]


In [32]:
# 내림차순 소팅
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬 : ', sort_array1_desc)

내림차순으로 정렬 :  [9 5 3 1]


In [34]:
array2d = np.array([[8, 12],[7, 1]])

sort_array2d_axis0 = np.sort(array2d, axis = 0)
print('로우 방향으로 정렬: \n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis = 1)
print('열 방향으로 정렬 : \n', sort_array2d_axis1)

로우 방향으로 정렬: 
 [[ 7  1]
 [ 8 12]]
열 방향으로 정렬 : 
 [[ 8 12]
 [ 1  7]]


#### 정렬된 행렬의 인덱스를 반환
- 원본행렬이 정렬되었을 때 원본 행렬의 원소에 대한 인덱스를 필요로 할때 np.argsort()를 이용.

np.argsort()를 이용해 원본 행렬의 정렬시 행렬 인덱스 값 구하기 

In [9]:
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬시 원본 행렬의 인덱스 : ', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬시 원본 행렬의 인덱스 :  [1 0 3 2]


In [ ]:
# 내림차순으로 정렬시에 원본 행렬의 인덱스를 구하는것도 np.argsort()[::-1]
org_array = np.array([3, 1, 9, 5])
sort_indices_desc = no.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스 : ',sort_indices_desc)

In [16]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Samuel', 'Kate', 'Sarah'])
score_array = np.array([78, 95, 84, 98, 88])


sort_indices_asc = np.argsort(score_array)

print('성적 오름차순 정렬시 score_array의 인덱스 : ', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력', name_array[sort_indices_asc])

성적 오름차순 정렬시 score_array의 인덱스 :  [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력 ['John' 'Samuel' 'Sarah' 'Mike' 'Kate']


### 선형대수 연산 - 행렬 내적과 전치 행렬 구하기 
- 행렬 내적 : 오른쪽 행렬의 행 갯수와 왼쪽 행렬의 열갯수가 동일해야 dot product가 에러가 안남

In [18]:
A = np.array([[1, 2, 3],
             [4, 5, 6]])
B = np.array([[7,8],
            [9, 10],
             [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 곱 \n: ', dot_product)

행렬 내적 곱 
:  [[ 58  64]
 [139 154]]


- 전치 행렬 : 원 행렬에서 행과 열 위치를 교환한 원소로 구성된 행렬을 그 행렬의 전치 행렬이라고 함.

In [20]:
A = np.array([[1, 2],
              [3, 4]])
              
transpose_mat = np.transpose(A)
print('A의 전치행렬 : \n', transpose_mat)              

A의 전치행렬 : 
 [[1 3]
 [2 4]]
