## 난수발생과 카운팅
* random 서브 패키지 
* seed값 설정

In [1]:
import numpy as np

### 시드값 설정

In [2]:
np.random.seed(0)

In [8]:
# 0과 1사이의 난수값 5개 발생
np.random.rand(5)

array([0.63992102, 0.14335329, 0.94466892, 0.52184832, 0.41466194])

In [10]:
np.random.rand(10)

array([0.3595079 , 0.43703195, 0.6976312 , 0.06022547, 0.66676672,
       0.67063787, 0.21038256, 0.1289263 , 0.31542835, 0.36371077])

In [12]:
np.random.rand(10)

array([0.15896958, 0.11037514, 0.65632959, 0.13818295, 0.19658236,
       0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841])

In [14]:
np.random.seed(0)

In [16]:
np.random.rand(5)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [18]:
np.random.rand(10)

array([0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443,
       0.63992102, 0.14335329, 0.94466892, 0.52184832, 0.41466194])

In [34]:
np.random.rand(10)

array([0.16469416, 0.6214784 , 0.57722859, 0.23789282, 0.934214  ,
       0.61396596, 0.5356328 , 0.58990998, 0.73012203, 0.311945  ])

### 데이터의 순서 바꾸기 

In [37]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.random.shuffle(x)
x

array([5, 1, 4, 6, 3, 9, 0, 7, 8, 2])

## 데이터 샘플링
numpy.random.choice(a, size = None, replae = True, p=None)
* a: 배열이면 원래의 데이터, 정수이면 arange(a) 명령으로  데이터 생성
* size : 정수, 샘플 숫자
* replace : booena, True이면 한번 선택한 데이터를 다시 선택
* p : 배열, 각 데이터가 선택될 수 있는 확률

In [44]:
np.random.choice(5, 5, replace=False)  # shuffle 명령과 같다.

array([0, 4, 2, 1, 3])

In [46]:
np.random.choice(5, 3, replace = False)                                                                                                                                                                              
    

array([3, 4, 0])

In [66]:
np.random.choice(5, 10) # 0부터 4까지의 숫자를 10개 

array([0, 0, 4, 4, 0, 4, 4, 2, 0, 4])

## 난수 생성
* rand : 0부터 1사이의 균일분포
* randn : 표준 정규분포(기대값이 0이고 표준편차가 1인 표준 정규분포인 난수 생성)
* randint : 균일분포의 정수 난수 

In [68]:
np.random.rand(10) # 0부터 1사이의 실수 난수 10개를 생성

array([0.25146379, 0.93229531, 0.99300131, 0.16453272, 0.51290532,
       0.86347622, 0.34769799, 0.24263733, 0.73106521, 0.97751782])

In [69]:
np.random.rand(3, 5)   # 3행 5열의 0부터 1사이의 수를 리턴

array([[0.50374782, 0.39243057, 0.39193287, 0.79450646, 0.70606101],
       [0.31891733, 0.97458866, 0.89158049, 0.70092806, 0.44077719],
       [0.20729598, 0.6649647 , 0.75389007, 0.60407755, 0.49561678]])

In [70]:
np.random.randn(10)   # 10개의 표준정규분포를 이루는 난수 생성

array([ 0.26279563, -0.3525333 ,  1.17390053, -0.02787465, -0.79000299,
       -0.01625444,  0.5152652 , -0.28143394,  0.10263516, -0.03623992])

In [72]:
np.random.randn(3, 5)  # 3행 5열의 표준정규분포를 이루는 난수 생성

array([[ 0.82293674, -0.42394496, -0.29928932, -0.02557865, -0.5789237 ],
       [ 0.88292964,  0.1951693 , -0.2148443 ,  0.67505911,  0.07998473],
       [ 0.75275396, -1.25719337,  0.28985118, -0.31398504, -0.47184063]])

randint함수는 다음과 같은 인수를 가지낟.
* numpy.random.rnadint(low, high=None, size = None)
* hight를 입력하지 않으면 0과 low값 사이의 숫자를,hight를 입력하면 low,high값 사이의 숫자를 출력
* size는 난수의 갯수

In [77]:
np.random.randint(10, size = 10)

array([2, 5, 4, 1, 0, 2, 5, 4, 2, 7])

In [79]:
np.random.randint(10, 20, size = 10)

array([11, 15, 19, 15, 12, 13, 13, 13, 18, 15])

In [80]:
np.random.randint(10, 20, size = (3, 5))

array([[19, 15, 11, 18, 17],
       [17, 11, 19, 10, 19],
       [14, 16, 10, 13, 13]])

### 연습문제 3.5.1

#### 동전을 10번던져 앞면(숫자1), 뒷면(숫자 0)이 나오는 가상시험

In [54]:
np.random.randint(0,2 , size = 10)

array([0, 0, 1, 1, 1, 0, 0, 1, 0, 0])

#### 주사위를 100번 던져 나오는 수의 합계 구하기 

In [65]:
np.sum(np.random.randint(low = 1, high = 7, size = 100))

367

### 연습문제 3.5.2
가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하라

In [75]:
np.random.randn(250) * 10000

array([ 14708.09067693, -10770.70900217,  15151.49990838,   -812.53700323,
        -8684.14437938,   3452.77163152,   3282.31127502,  10008.36956956,
         1238.71826513,   5483.56364566,   -445.83817888,  14867.51116523,
        15468.49001079,  18683.91669577,  -1330.96897131,  -5227.68160612,
       -10330.7527006 ,  -2167.96526847, -12712.11550145,  -7070.0454494 ,
         7847.01215911,   1025.18285009,   -743.98050401,  -5297.69048775,
        -6126.98216383,   2470.37248393, -15689.14515665,  13420.13470824,
        -7694.94996764,   8087.81352161,  28762.20127455,  -2426.12738847,
         2659.16823824, -14720.72815607,  -9660.77163962,   8411.86946985,
        -3765.42402519,  10579.63184439,   8885.75346064, -16526.43037314,
        -9422.43386252,  -2357.95054021,  11359.87950046,  -2892.98881181,
        24008.79049595,   5118.14820217, -10824.04295354,  -4678.41984485,
        15717.02520699,  21260.19131332,  -2715.71350479,   2862.03834175,
       -10073.27066828, -