## 난수발생과 카운팅
* random 서브 패키지 
* seed값 설정

In [1]:
import numpy as np

### 시드값 설정
* 컴퓨터 프로그램에서 발생하는 무작위 수는 사실 엄격한 무작위 수가 아니다. 어떤 특정한 시작 숫자를 정해주면 컴퓨터가 정해진 알고리즘에 의해 마치 난수처럼 보이는 수열을 생성한다.
* 일단 생성된 난수는 다음 번 난수 생성을 위한 시드값이 된다.따라서 시드값은 한 번만 정해주면 된다. 코드의 결과를 재현하기 위해 항상 시드를 설정한다.

In [2]:
np.random.seed(0)

In [3]:
# 0과 1사이의 난수값 5개 발생
np.random.rand(3, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318],
       [0.4236548 , 0.64589411]])

In [4]:
np.random.rand(10)

array([0.43758721, 0.891773  , 0.96366276, 0.38344152, 0.79172504,
       0.52889492, 0.56804456, 0.92559664, 0.07103606, 0.0871293 ])

In [5]:
np.random.rand(10)

array([0.0202184 , 0.83261985, 0.77815675, 0.87001215, 0.97861834,
       0.79915856, 0.46147936, 0.78052918, 0.11827443, 0.63992102])

In [6]:
np.random.seed(0)

In [7]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [8]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [9]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

### 데이터의 순서 바꾸기 

In [10]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.random.shuffle(x)
x

array([3, 6, 4, 5, 2, 9, 7, 8, 1, 0])

## 데이터 샘플링
numpy.random.choice(a, size = None, replae = True, p=None)
* a: 배열이면 원래의 데이터, 정수이면 arange(a) 명령으로  데이터 생성
* size : 정수, 샘플 숫자
* replace : booena, True이면 한번 선택한 데이터를 다시 선택
* p : 배열, 각 데이터가 선택될 수 있는 확률

In [12]:
np.random.choice(5, 5, replace=False)  # shuffle 명령과 같다.

array([1, 4, 0, 3, 2])

In [13]:
np.random.choice(5, 3, replace = False)                                                                                                                                                                              
    

array([2, 1, 3])

In [14]:
np.random.choice(5, 10) # 0부터 4까지의 숫자를 10개 

array([0, 4, 1, 4, 1, 2, 2, 0, 1, 1])

## 난수 생성
* rand : 0부터 1사이의 균일분포
* randn : 표준 정규분포(기대값이 0이고 표준편차가 1인 표준 정규분포인 난수 생성)
* randint : 균일분포의 정수 난수 

In [15]:
np.random.rand(10) # 0부터 1사이의 실수 난수 10개를 생성

array([0.09928035, 0.96980907, 0.65314004, 0.17090959, 0.35815217,
       0.75068614, 0.60783067, 0.32504723, 0.03842543, 0.63427406])

In [16]:
np.random.rand(3, 5)   # 3행 5열의 0부터 1사이의 수를 리턴

array([[0.95894927, 0.65279032, 0.63505887, 0.99529957, 0.58185033],
       [0.41436859, 0.4746975 , 0.6235101 , 0.33800761, 0.67475232],
       [0.31720174, 0.77834548, 0.94957105, 0.66252687, 0.01357164]])

In [17]:
np.random.randn(10)   # 10개의 표준정규분포를 이루는 난수 생성

array([ 1.50944508,  1.06777513, -0.68658948,  0.01487332, -0.3756659 ,
       -0.03822364,  0.36797447, -0.0447237 , -0.30237513, -2.2244036 ])

In [18]:
np.random.randn(3, 5)  # 3행 5열의 표준정규분포를 이루는 난수 생성

array([[ 0.72400636,  0.35900276,  1.07612104,  0.19214083,  0.85292596],
       [ 0.01835718,  0.42830357,  0.99627783, -0.49114966,  0.71267817],
       [ 1.11334035, -2.15367459, -0.41611148, -1.07089699,  0.22113881]])

randint함수는 다음과 같은 인수를 가지낟.
* numpy.random.rnadint(low, high=None, size = None)
* hight를 입력하지 않으면 0과 low값 사이의 숫자를,hight를 입력하면 low,high값 사이의 숫자를 출력
* size는 난수의 갯수

In [19]:
np.random.randint(10, size = 10)

array([2, 0, 8, 8, 3, 8, 2, 8, 4, 3])

In [20]:
np.random.randint(10, 20, size = 10)

array([10, 14, 13, 16, 19, 18, 10, 18, 15, 19])

In [21]:
np.random.randint(10, 20, size = (3, 5))

array([[10, 19, 16, 15, 13],
       [11, 18, 10, 14, 19],
       [16, 15, 17, 18, 18]])

### 연습문제 3.5.1

#### 동전을 10번던져 앞면(숫자1), 뒷면(숫자 0)이 나오는 가상시험

In [22]:
np.random.randint(0,2 , size = 10)

array([1, 1, 0, 0, 0, 1, 1, 0, 1, 1])

#### 주사위를 100번 던져 나오는 수의 합계 구하기 

In [23]:
np.sum(np.random.randint(low = 1, high = 7, size = 100))

374

### 연습문제 3.5.2
가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하라

In [24]:
np.random.randn(250) * 10000

array([-11230.57115379, -18112.78790918,  -6311.75217748,  -9281.5918457 ,
        14907.21916959,   1954.99335275,  -4716.04333548,  18123.54651531,
       -22941.37478799,   6512.09345842, -11304.96449502,  -7773.46655762,
        11159.38454123,  13394.53016548, -17674.33651389,   4244.12458828,
        10893.09045105,  -3841.85680998,   6322.0141416 ,  -5496.5590088 ,
         5211.25739509,   1083.49548763,   2616.68476887,  -9147.55330099,
         8582.37785355,    943.34289976, -14859.03858648, -19005.84261243,
       -11375.79197031, -17620.38885039,  -2886.2321917 ,  10479.82224693,
         2499.57540819,    469.04461519, -10322.43036731,   4031.85681555,
        -6840.59252016,  12623.22186207, -20055.56590963,  -3320.30396466,
        -2961.00402904, -22183.60756564,  -1835.02879002,   3923.08055656,
         2416.34806555,   1039.35912278,  -8295.71186637,   4927.59391416,
          901.12790984,  -9975.67538838,  -8000.38214395,   2070.75574055,
         5234.63027189,  

### 정수 데이터 카운팅
* 난수가 정수값이면 `unique` 이나 `bincount`함수 이용

In [29]:
t1 = [11, 11, 2, 2, 34, 34]

In [30]:
np.unique(t1)  # 고유한 값만 리턴

array([ 2, 11, 34])

In [28]:
help(np.unique)

Help on function unique in module numpy:

unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None)
    Find the unique elements of an array.
    
    Returns the sorted unique elements of an array. There are three optional
    outputs in addition to the unique elements:
    
    * the indices of the input array that give the unique values
    * the indices of the unique array that reconstruct the input array
    * the number of times each unique value comes up in the input array
    
    Parameters
    ----------
    ar : array_like
        Input array. Unless `axis` is specified, this will be flattened if it
        is not already 1-D.
    return_index : bool, optional
        If True, also return the indices of `ar` (along the specified axis,
        if provided, or in the flattened array) that result in the unique array.
    return_inverse : bool, optional
        If True, also return the indices of the unique array (for the specified
        axis, if pro

In [33]:
index, count = np.unique(t1, return_counts = True)

In [35]:
index

array([ 2, 11, 34])

In [37]:
count

array([2, 2, 2], dtype=int64)

In [39]:
t2 = ['a', 'b', 'b', 'c', 'a']

In [44]:
a = np.array(t2)
index, count = np.unique(a, return_counts = True)
index, count

(array(['a', 'b', 'c'], dtype='<U1'), array([2, 2, 1], dtype=int64))

* bincount 함수는 0 부터 minlength - 1 까지의 숫자에 대해 각각 카운트를 한다. 데이터가 없을 경우에는 카운트 값이 0이 됨

In [45]:
help(np.bincount)

Help on function bincount in module numpy:

bincount(...)
    bincount(x, weights=None, minlength=0)
    
    Count number of occurrences of each value in array of non-negative ints.
    
    The number of bins (of size 1) is one larger than the largest value in
    `x`. If `minlength` is specified, there will be at least this number
    of bins in the output array (though it will be longer if necessary,
    depending on the contents of `x`).
    Each bin gives the number of occurrences of its index value in `x`.
    If `weights` is specified the input array is weighted by it, i.e. if a
    value ``n`` is found at position ``i``, ``out[n] += weight[i]`` instead
    of ``out[n] += 1``.
    
    Parameters
    ----------
    x : array_like, 1 dimension, nonnegative ints
        Input array.
    weights : array_like, optional
        Weights, array of the same shape as `x`.
    minlength : int, optional
        A minimum number of bins for the output array.
    
        .. versionadded:: 

In [47]:
np.bincount(np.arange(5))  # 각각의 원소가 등장하는 빈도수를 리턴

array([1, 1, 1, 1, 1], dtype=int64)

In [49]:
np.bincount(np.array([0, 1, 1, 3, 2, 1, 7]))

array([1, 3, 1, 1, 0, 0, 0, 1], dtype=int64)

In [52]:
np.bincount(np.array([1, 1, 1, 3, 2, 1, 7, 8, 8]))  # minlength = 0

array([0, 4, 1, 1, 0, 0, 0, 1, 2], dtype=int64)