# 벡터와 행렬의 연산

In [1]:
import numpy as np
import matplotlib.pyplot as plt

## 벡터/행렬의 덧셈과 뺄셈
* 같은 위치에 있는 원소끼라 연산이 이루어짐.

In [2]:
x = np.array([10, 11, 12, 13, 14])
y = np.array([0, 1, 2, 3, 4])

In [3]:
add = x + y
sub = x - y

In [4]:
display(add, sub)

array([10, 12, 14, 16, 18])

array([10, 10, 10, 10, 10])

In [5]:
np.array([[5,6], [7, 8]]) + np.array([[10, 20], [30, 40]]) - np.array([[1, 2], [3, 4]])

array([[14, 24],
       [34, 44]])

### 스칼라와 벡터/행렬의 곱셈
* 벡터 $x$ 또는 행렬 $A$에 스칼라 $c$를 곱하는 것은 벡터 $x$ 또는 행렬 $A$의 모든 원소에 스칼라값 $c$를 곱하는것과 같다.

### 브로드캐스팅
* 원래 덧셈과 뺄셈은 크기(차원)가 같은 두 벡터에 대해서만 할 수 있다. 하지만 벡터와 스칼라의 경우에는 모든 원소에 대해서 연산이 가능하다.

### 선형조합
* 벡터/행렬에 스칼라 값을 곱한 후 더하거나 뺀것을 벡터/행렬의 선형조합이라고 한다.벡터나 선형조합해도 크기는 변하지 않는다.

### 벡터와 벡터의 곱셈
* 내적(inner product) 혹은 dot product라고 함.
* 우선 두 벡터의 차원의 길이가 같아야 하고, 앞의 벡터가 행벡터이고 뒤의 벡터가 열벡터이어야 한다.(**앞의 행과 뒤의 열이 같아야 함**)

In [6]:
x = np.array([[1], [2], [3]])
y = np.array([[4], [5], [6]])

display(x.T@ y, np.dot(x.T,y))

array([[32]])

array([[32]])

* 넘파이에서는 1차원 배열끼리고 내적을 계산

In [7]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [8]:
display(x.T@ y, np.dot(x.T,y))

32

32

### 가중합
* 벡터의 내적은 가중합을 계산할때 쓰이며, 가중합(weighted sum)이란 복수의 데이터를 단순히 합하는것이 아니라, 각각의 수에 가중치를 곱한 후 이 곱셈 결과를 다시 합한 것을 말함.

### 2.2.1 연습문제
A, B, C세 회사의 주식은 각각 100만원, 80만원, 50만원이다. 이 주식을 각각 3주, 4주, 5주를 매수할때 필요한 금액을 구하고자 한다.

1) 주식의 가격과 수량을 각각 $p$벡터 , $n$벡터로 표시하고 넘파이로 코딩

2) 주식을 매수할때 필요한 금액을 곱셈으로 표시하고 값 계산

In [9]:
p = np.array([[100], [80], [50]])
n = np.array([[3], [4], [5]])

In [10]:
np.dot(n.T, p)

array([[870]])

### 가중평균
* 가중치의 가중치값을 전체 가중치값의 합으로 나누면 **가중평균** 이 된다.

In [15]:
#넘파이의 평균 게산
x = np.arange(10)
N = len(x)
x1 = np.ones(N)
display(x1, x)

x1 @ x / N

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

4.5

In [17]:
x.mean()

4.5

### 유사도
* 벡터의 곱셈(내적)은 두 벡터간의 유사도를 계산하는데 이용한다. **유사도(similarity)**는 두 벡터가 닮은 정도를 정량적으로 나타낸 값**으로 두 벡터가 비슷한 경우에는 유사도가 커지고 비슷하지 않은 경우엔 유사도가 작아진다.
* 내적을 이용하면 **코사인 유사도**라는 유사도를 계산 할 수 있다.

**`0`과 `1`을 나타내는 MNIST이미지에 대한 내적 계산**

In [22]:
from sklearn.datasets import load_digits
import matplotlib.gridspec as gridspec  # subplot의 크기를 각각 달리 줄수 있다.

digits = load_digits()
digits.keys()

dict_keys(['data', 'target', 'frame', 'feature_names', 'target_names', 'images', 'DESCR'])

In [25]:
display(digits.images.shape)

(1797, 8, 8)

In [27]:
digits.images[0]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [30]:
d1 = digits.images[0]
d2 = digits.images[10]
d3 = digits.images[1]
d4 = digits.images[11]

v1 = d1.reshape(64, 1) # 64행 * 1열을 갖는 벡터로 변환
v2 = d2.reshape(64, 1)
v3 = d3.reshape(64, 1)
v4 = d4.reshape(64, 1)


plt.figure(figsize = (9,9))
gs = gridspec.GridSpec(nrows = 1, ncols = 8, width_ratios = [9, 1, 9, 1, 9, 1, 9, 1]) # subplot의 크기를 다르게 조정이 가능
gs

GridSpec(1, 8, width_ratios=[9, 1, 9, 1, 9, 1, 9, 1])

<Figure size 648x648 with 0 Axes>