<a href="https://colab.research.google.com/github/SANGSEOSEO/philosophy_datascience/blob/master/%5B%EC%8B%A4%EC%8A%B5%5DCh06_numpy_04~06_index%EC%99%80_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## 1. 슬라이싱 (Slicing)

배열의 부분 선택 (과일을 슬라이스해서 부분만 먹듯..)

In [7]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr.shape

(10,)

### 1-1. index 지정하여 색인

#### 1차원 array

In [9]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# 배열의 추출과 동일
arr[0]

0

In [12]:
# 코드를 입력해 주세요
arr[5]

5

In [14]:
# IndexError: index 10 is out of bounds for axis 0 with size 10
arr[10]

IndexError: ignored

In [15]:
# -1 : 뒤에서 부터 인덱싱
arr[-1], arr[8]

(9, 8)

In [17]:
# 코드를 입력해 주세요
arr[-10]  # a[0]과 동일

0

#### 2차원 array

In [19]:
arr2d = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

In [20]:
arr2d.shape

(3, 4)

arr2d[행, 열]

In [21]:
# 코드를 입력해 주세요
arr2d[0, 2]

3

In [22]:
# 코드를 입력해 주세요
arr2d[2, 1]

10

### 1-2. 범위 색인

#### 1차원

index 1**이상** 끝까지

In [24]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# 1번 인덱스부터 끝까지 다 가져와.
arr[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 코드를 입력해 주세요
arr[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

index 5 **미만** 까지

In [25]:
# 5번째 인덱스는 포함되지 않음
arr[:5]

array([0, 1, 2, 3, 4])

index 1이상 5미만

In [26]:
# 시작점은 포함되고 끝점은 포함되지 않음
arr[1:5]

array([1, 2, 3, 4])

In [29]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
# arr[-1]이 9이므로 9는 포함안되고, 0부터 8까지만 가져옴
arr[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

#### 2차원

In [ ]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

row(행)을 모두 가져오려는 경우

In [ ]:
# 0번째 로우를 가져오되, 컬럼은 다 가져와라
# `:`의 의미는 다 가져오라는 의미
arr2d[0, :]

array([1, 2, 3, 4])

column(열)을 모두 가져오려는 경우

In [31]:
# 행은 모든 행은 다 가져오는데 컬럼은 2번째 행만 가져옴
arr2d[:, 2]

array([ 3,  7, 11])

부분적으로 가져오려는 경우

In [35]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
# 행은 0번째부터 1번째 까지 가져오고 로우는 모두 다 가져와라.
# 열에는 `:`표시 이므로 컬럼(열)은 다가져와라.
arr2d[0:2,:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [37]:
# 행은 0번째 부터 1번째까지 가져오고 열(컬럼)은 2번째 인덱스부터 다 가져와.
arr2d[0:2 , 2:] # arr2d[:2, 2:]와 동일

array([[3, 4],
       [7, 8]])

## 2. Fancy 인덱싱

fancy 인덱싱은 범위가 아닌 **특정 index의 집합의 값을 선택하여 추출**하고 싶을 때 활용합니다.

In [38]:
arr = np.array([10, 23, 2, 7, 90, 65, 32, 66, 70])

반드시 **[추출하고 싶은 인덱스]** 꺾쇠 괄호로 묶어 주세요

변수에 지정 후 추출도 가능합니다.

> boolean indexing이랑 비슷한 것 같아.



In [39]:
# 가져오고자 하는 인덱스 설정
idx = [1, 3, 5]

In [40]:
arr[idx]

array([23,  7, 65])

### 2-2. 2차원 array

In [ ]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [43]:
# 코드를 입력해 주세요
# 행은 0번째부터 1번째까지만 가져오고 컬럼은 다 가져오세요
# 앞에는 행, 뒤에는 열
arr2d[0:2,:] 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [44]:
# Fancy indexing
arr2d[[0, 1], :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [46]:
# 행은 다 가져오고, 열은 지정된 인덱스의 열을 다 가져옴
arr2d[:, [1, 2, 3]]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [47]:
# 행(로우)는 다 가져오고 컬럼은 1번째 인덱스부터만 가져와.
arr2d[:,1:]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [48]:
# 행(로우)는 다 가져오고, 컬럼은 1번,2번, 3번 인덱스만 가져와.
arr2d[:, [1, 2, 3]]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

## 3. Boolean 인덱싱

조건 필터링을 통하여 Boolean 값을 이용한 색인 (말이 어렵다..)

In [52]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [53]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

### 3-1. True와 False 값으로 색인하기

In [54]:
myTrueFalse = [True, False, True]

In [56]:
# IndexError: boolean index did not match indexed array along dimension 0; dimension is 7 but corresponding boolean dimension is 3
arr[myTrueFalse]

IndexError: ignored

In [61]:
# 본대로 바와 같이 True인 것만 가져온다.
myTrueFalse_T = [True, False, True, False, True, False, True]

In [62]:
arr[myTrueFalse_T]

array([1, 3, 5, 7])

In [63]:
myTrueFalse_T1 = [True, False, True, False, True, False, True]
arr[myTrueFalse_T1]


array([1, 3, 5, 7])

In [ ]:
arr[myTrueFalse_T1]

array([1, 3, 5, 7])

### 3-2. 조건필터

조건 연산자를 활용하여 필터를 생성할 수 있습니다

In [64]:
arr2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
# 조건에 만족 여부 확인_boolean index
arr2d > 2

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [67]:
arr2d[arr2d > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

필터를 활용하여 필터에 True 조건만 색인 합니다.

이럴 때 꺾쇠 괄호로 한 번 더 묶어만 주면 됩니다. (꺾쇠 괄호 안에 조건문 삽입) 

arr2d[**조건필터**]

In [68]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [69]:
# 2이상인 것들만 가져와줘.
arr2d[arr2d > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [70]:
# 5보다 작은 것을 가져와.
arr2d[arr2d < 5]

array([1, 2, 3, 4])