<a href="https://colab.research.google.com/github/SANGSEOSEO/philosophy_datascience/blob/master/%5B%EC%8B%A4%EC%8A%B5%5DCh06_numpy_10~12_matrix_arithmatic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

## 1. 행렬 - 덧셈
 - shape이 같아야 한다.
 - 같은 position끼리 연산합니다.

### 1-1. 덧셈

In [ ]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [ ]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [ ]:
a.shape, b.shape

((2, 3), (2, 3))

In [ ]:
# shape이 동일해야 연산이 가능
a + b

array([[4, 6, 8],
       [3, 5, 7]])

In [ ]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [ ]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [ ]:
a.shape, b.shape

((2, 3), (3, 2))

In [1]:
# shape이 동일해야 한다.
a + b

NameError: ignored

### 1-2. Sum

In [5]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [8]:
# 행으로 sum
np.sum(a, axis=0)

array([3, 5, 7])

In [9]:
# 열로 sum
np.sum(a, axis=1)

array([6, 9])

## 2. 행렬 - 뺄셈
 - 덧셈과 마찬가지로 shape이 같아야 한다.

In [ ]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [ ]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [ ]:
# matrix간 sub
a - b


array([[-2, -2, -2],
       [ 1,  1,  1]])

In [ ]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [ ]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [ ]:
# ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 
a - b

ValueError: ignored

In [ ]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])

In [ ]:
b = np.array([[3, 5, 3]])

In [ ]:
a.shape, b.shape

((2, 3), (1, 3))

In [ ]:
# broadcasting으로 다 뺀다.
a - b

array([[-2, -3,  0],
       [-1, -2,  1]])

## 3. 곱셈

일반 곱셈


> 맞닫는 shape이 같아야 한다.



In [10]:
a = np.array([
              [1, 2, 3],
              [4, 5, 6]
])

In [11]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [12]:
a.shape, b.shape

((2, 3), (2, 3))

In [13]:
# 코드를 입력해 주세요
a * b

array([[ 3,  8, 15],
       [ 4, 10, 18]])

In [14]:
a.shape, b.shape

((2, 3), (2, 3))

단순 곱셈과 dot product는 다릅니다. 이점 유의하세요!
 - **단순곱셈** 일반 더하기 빼기와 동일하며  **dot product**의 경우엔 맞닫는 shape이 동일해야 한다.

In [28]:
a = np.array([[1, 2, 3], 
              [1, 2, 3],
              [2, 3, 4]])

In [29]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [30]:
a.shape, b.shape

((3, 3), (2, 3))

In [31]:
# valueError: operands could not be broadcast together with shapes (3,3) (2,3) 
a * b

ValueError: ignored

In [32]:
# ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)
# shape의 맞닫는 면이 서로 다르다.
a.shape, b.shape

((3, 3), (2, 3))

In [33]:
# dot product시 에러
a.dot(b)

ValueError: ignored

In [35]:
b = np.array(
    [
     [1, 2],
     [3, 4],
     [5, 6]
    ]
)

In [36]:
a.shape, b.shape

((3, 3), (3, 2))

In [38]:
# dot product
a.dot(b)   # np.dot(a, b)

array([[22, 28],
       [22, 28],
       [31, 40]])

In [ ]:
1*1 + 2*3 + 3*5

22

In [39]:
np.dot(a, b)

array([[22, 28],
       [22, 28],
       [31, 40]])

In [ ]:
1*2 + 2*4 + 3*6

28