<a href="https://colab.research.google.com/github/SANGSEOSEO/philosophy_datascience/blob/master/%5B%EC%8B%A4%EC%8A%B5%5DCh06_numpy_13_%EB%B8%8C%EB%A1%9C%EB%93%9C%EC%BA%90%EC%8A%A4%ED%8C%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## 1. Broadcasting

## 1-1. 숫자의 연산 (단일)

In [2]:
a= np.array(
    [
     [1, 2, 3],
     [2, 3, 4]
    ]
)

In [3]:
b = np.array([[3, 3, 3], 
              [3, 3, 3]])

In [4]:
# 코드를 입력해 주세요
a + b

array([[4, 5, 6],
       [5, 6, 7]])

In [5]:
# broadcasting
a + 3

array([[4, 5, 6],
       [5, 6, 7]])

In [6]:
# broadcasting
a - 3

array([[-2, -1,  0],
       [-1,  0,  1]])

In [7]:
# scalar broadcasting
a * 3

array([[ 3,  6,  9],
       [ 6,  9, 12]])

In [8]:
# 코드를 입력해 주세요
a / 3

array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 1.        , 1.33333333]])

### 1-2. array(배열)의 브로드캐스팅

오리지널 array의 shape가 유지됨을 잘 보세요

In [9]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

In [10]:
b = np.array([[1], 
              [2]])

In [11]:
a.shape, b.shape

((2, 3), (2, 1))

In [12]:
# 덧셈 ,뺄셈의 원리와 동일하게 동일한 Position에 대해서 곱한다.
a * b

array([[ 1,  2,  3],
       [ 8, 10, 12]])

In [13]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [14]:
b = np.array([1, 2, 3])

In [15]:
# 코드를 입력해 주세요
a * b

array([[ 1,  4,  9],
       [ 2,  6, 12]])

##정리

 - dot product와 일반 곱셈은 방법이 약간 차이가 있다.
  - 전자는 맞닿는 부분의 shape이 일치해야 곱이 가능하다.
  - 후자는 shape이 같아야 하고,broadcasting이 동시에 일어난다.
- 덧셈, 뺄셈은 동일한 shape이어야 하고 , 동일 Positon의 인덱스를 가진 요소들끼리 연산