<a href="https://colab.research.google.com/github/SANGSEOSEO/philosophy_datascience/blob/master/%5B%EC%8B%A4%EC%8A%B5%5DCh06_numpy_08~09_%EC%A0%95%EB%A0%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## 1. 1차원 정렬

1차원 정렬은 매우 간단합니다.

In [2]:
arr = np.array([1, 10, 5, 8, 2, 4, 3, 6, 8, 7, 9])

In [3]:
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

np.sort(arr)

In [5]:
# 정렬을 해서 복사본을 리턴합니다.
# 원본은 그대로임.
np.sort(arr), arr

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10]),
 array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9]))

기본적으로 오름차순 정렬을 수행합니다.

In [14]:
# 외우자.내림차순으로 된다.
np.sort(arr)[::-1]

array([10,  9,  8,  8,  7,  6,  5,  4,  3,  2,  1])

내림차순 정렬은 옵션에 -1 값을 주면됩니다.

하지만, 이 값들은 **유지가 되지 않습니다**!

값을 sort 된 상태로 저장하려면, 배열 자체에 sort를 해줄 수 있습니다.

In [ ]:
np.sort(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [ ]:
# 새로운 변수에 할당해서 쓰거나 혹은 원래 변수에 정렬한 결과를 할당하는 것으로 사용.
arr2 = np.sort(arr)  # arr = np.sort(arr)

In [ ]:
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

In [ ]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [15]:
# 원본을 정렬함.None을 리턴. None이라는 의미는 원본을 변경한다는 의미이다.
arr.sort()

In [16]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

## 2. N차원 정렬

In [18]:
arr2d = np.array([[5, 6, 7, 8], 
                  [4, 3, 2, 1],
                  [10, 9, 12, 11]])

In [19]:
arr2d.shape

(3, 4)

In [20]:
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10,  9, 12, 11]])

### 2-1. 열 정렬 (왼쪽에서 오른쪽으로)

In [ ]:
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10,  9, 12, 11]])

In [21]:
# 열 기준으로 정렬해줘.
np.sort(arr2d, axis=1)

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

### 2-2. 행 정렬 (위에서 아래로)

In [22]:
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10,  9, 12, 11]])

In [24]:
# 행 기준으로 정렬
np.sort(arr2d,axis=0)

array([[ 4,  3,  2,  1],
       [ 5,  6,  7,  8],
       [10,  9, 12, 11]])

## 3. index를 반환하는 argsort

정렬된 값을 반환하는 것이 아닌 index를 반환합니다.

In [25]:
arr2d = np.array([[5, 6, 7, 8], 
                  [4, 3, 2, 1],
                  [10, 9, 12, 11]])


### 3-1. 열 정렬 (왼쪽에서 오른쪽으로)

In [27]:
# 어떤 값을 데이터 분석할때 해당 값의 인덱스를 받아오고 싶을때 사용
np.argsort(arr2d, axis=1)

array([[0, 1, 2, 3],
       [3, 2, 1, 0],
       [1, 0, 3, 2]])

### 3-2. 행 정렬

In [ ]:
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10,  9, 12, 11]])

In [28]:
# 코드를 입력해 주세요
np.argsort(arr2d, axis=0)

array([[1, 1, 1, 1],
       [0, 0, 0, 0],
       [2, 2, 2, 2]])

In [ ]:
# 코드를 입력해 주세요


array([[1, 1, 1, 1],
       [0, 0, 0, 0],
       [2, 2, 2, 2]])