<a href="https://colab.research.google.com/github/SANGSEOSEO/philosophy_datascience/blob/master/%5B%EC%8B%A4%EC%8A%B5%5DCh06_numpy_02~03_numpy_ndarray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Numpy import 하기

 - 수치/과학 계산용 패키지
 - ndarray : n Dimension array(n차원 배열)

In [1]:
import numpy as np

In [ ]:
np

<module 'numpy' from '/usr/local/lib/python3.6/dist-packages/numpy/__init__.py'>

### 1-1. 별칭 (alias) 지정하기 (항상 해주세요!)

In [9]:
# 코드를 입력해 주세요
import numpy as np

## 2. ndarray 생성하기

 **shape**은 차원의 수를 확인
- (3,) => 3 X 1의 배열
- (4, 3) => 4 X 3 의 배열
- (2, 5, 3) => 2 X 5 X 3의 배열

**axis**는 기준이 되는 축

In [2]:
# ndarray 생성
arr = np.array([1, 2, 3, 4], dtype=int)

In [3]:
arr

array([1, 2, 3, 4])

In [5]:
[1, 2, 3, 4]

[1, 2, 3, 4]

In [4]:
type(arr)

numpy.ndarray

### 2-1. list로 부터 생성하기

In [18]:
mylist1 = [1, 2, 3, 4]

In [19]:
mylist2 = [[1, 2, 3, 4,],[5, 6, 7, 8]]

In [20]:
arr1 = np.array(mylist1)

In [21]:
arr2 = np.array(mylist2)


### 2-2. shape확인하기

In [22]:
# arr1의 shape 확인 : 1차원의 갯수는 4개이다.
arr1.shape

(4,)

In [23]:
# arr2의 shape확인(행이 2개이고 컬럼이 4개이다)
arr2.shape


(2, 4)

## 3. array에서의 data 타입

array에서는 list와는 다르게 1개의 **단일 데이터 타입**만 허용 됩니다.

### 3-1. list에서의 data 타입

In [24]:
mylist = [1, 3.14, '테디', '1234']

In [25]:
mylist

[1, 3.14, '테디', '1234']

In [26]:
# 코드를 입력해 주세요
arr = np.array([1, 2, 3.14, 4, 5])

In [28]:
# int형이 str타입을 따라간다.(U21)
arr_t = np.array([1, 2, 3, 'B'])
arr_t

array(['1', '2', '3', 'B'], dtype='<U21')

In [29]:
arr

array([1.  , 2.  , 3.14, 4.  , 5.  ])

In [30]:
# 코드를 입력해 주세요
mylist[2]

'테디'

### 3-2. array에서의 data 타입 (case를 통한 연구)

### case 1. int와 float 타입이 혼재된 경우

In [31]:
# dtype을 지정하지 않았다.
arr = np.array([1, 2, 3, 3.14])

In [32]:
arr

array([1.  , 2.  , 3.  , 3.14])

### case 2. int와 float 타입이 혼재되었으나, dtype을 지정한 경우

In [33]:
# 명시적으로 int형으로 지정
arr = np.array([1, 2, 3.14, 4], dtype='int')

In [34]:
arr

array([1, 2, 3, 4])

In [35]:
# dtype을 float으로 지정하면 지정한것으로 변환되어 ndarray가 생성
arr = np.array([1, 2, 3.14, 4.5, 5], dtype='float')

In [36]:
arr

array([1.  , 2.  , 3.14, 4.5 , 5.  ])

### case 3. int와 str 타입이 혼재된 경우

In [37]:
# int형이 str형으로 변환
arr = np.array([1, 3.14, '테디', '1234'])

In [38]:
#  dtype='<U32')
arr

array(['1', '3.14', '테디', '1234'], dtype='<U32')

In [ ]:
arr[0] + arr[1]

'13.14'

### case 4. int와 str 타입이 혼재되어 있고 int로 dtype을 지정한 경우

In [39]:
arr = np.array([1, 2, 3.14, 4, '100'],dtype='int' )

In [40]:
arr

array([  1,   2,   3,   4, 100])

In [41]:
# dtype을 str으로 명시적으로 지정해주면 다른 것들을 str으로 바꿈
arr_mix = np.array([1, 2, 3.14, 'sang'], dtype='str')

In [42]:
arr_mix

array(['1', '2', '3.14', 'sang'], dtype='<U4')

In [43]:
arr_mix[0]

'1'

In [44]:
arr_mix[3]

'sang'

##정리

- 파이썬은 일단 똑똑해.하지만 ndarray를 사용할때 반드시 동일한 데이터타입으로 ndarray를 만들어라.