# 데이터 전처리

## 데이터 인코딩
* Label encoding : 카테고리형 피처를 코드형 숫자값으로 변환
* One Hot Encoding : 피처값의 유형에 따라 새로운 피처를 추가해 고유 값에 해당하는 칼럼에만 `1`을 포함하고 나머지 컬럼에는 `0`을 표시

### 레이블 인코딩
* LabelEncoder클래스로 구현 : `fit()`과 `transform()`

In [4]:
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

# LabelEncoder객체를 생성한 후 ,fit()과 transform()으로 레이블 인코딩
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

print('인코딩 변환값 : ', labels)

인코딩 변환값 :  [0 1 4 5 3 3 2 2]


In [6]:
print('인코딩 클래스 : ', encoder.classes_)

인코딩 클래스 :  ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [11]:
print('디코딩 원본값 : ', encoder.inverse_transform([0, 1, 4, 5, 3, 3, 2, 2]))

디코딩 원본값 :  ['TV' '냉장고' '전자레인지' '컴퓨터' '선풍기' '선풍기' '믹서' '믹서']


### 원-핫 인코딩(One-Hot Encoding)

In [23]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

# 먼저 숫자값으로 변환을 위해 LabelEncoder로 변환합니다.
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

# 2차원 데이터로 변환합니다.
labels = labels.reshape(-1, 1)

# 원-핫 인코딩
oh_encode = OneHotEncoder()
oh_encode.fit(labels)
oh_labels = oh_encode.transform(labels)

print('One-Hot Encoding ')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

One-Hot Encoding 
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


#### `get_dummies()`를 이용한 원-핫 인코딩 

In [30]:
import pandas as pd

In [33]:
df = pd.DataFrame({'item':['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']})
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

## 피처 스케일링과 정규화
서로 다른 변수의 값의 범위를 일정한 수준으로 맞추는 작업을 말함.
* 표준화 : 데이터의 피처 각각이 평균이 `0`이고 분산이 `1`인 가우시안 정규분포를 가진값으로 변환
* 정규화 : 서로 다른 피처의 크기를 통일하기 위해 크기를 변환해주는 개념.즉, 개별 데이터의 크기를 모두 똑같은 단위로 변경하는것.

### StandardScaler
* 개별 피처를 평균이 `0`이고, 분산이 `1`인 값으로 변환(가우시안 정규분포)

In [8]:
from sklearn.datasets import load_iris
import pandas as pd

# 붓꽃 데이터 세트를 로딩하고 DataFrame으로 변환합니다.
iris = load_iris()
iris_data = iris.data
iris_df = pd.DataFrame(data = iris_data, columns = iris.feature_names)


print('feature들의 평균값')
print(iris_df.mean())

print('\nfeature들의 분산 값')
print(iris_df.std())

feature들의 평균값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature들의 분산 값
sepal length (cm)    0.828066
sepal width (cm)     0.435866
petal length (cm)    1.765298
petal width (cm)     0.762238
dtype: float64


In [12]:
from sklearn.preprocessing import StandardScaler

#StandardScaler객체 생성
scaler = StandardScaler()

# StandardScaler로 데이터 세트 변환.
# fit() 과 transform()호출
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

print(type(iris_scaled), dir(iris_scaled))

<class 'numpy.ndarray'> ['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__r

In [14]:
#transform() 시 스케일변환된 데이터 세트가 numpy.ndarray()로 반환돼 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data = iris_scaled, columns = iris.feature_names)
print('feature들의 평균값')
print(iris_df_scaled.mean())
print('\nfeature들의 분산값')
print(iris_df_scaled.var())

feature들의 평균값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

feature들의 분산값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


* 모든 컬럼 값의 평균이 0에 아주 가까운 값으로 , 그리고 분산은 1에 아주 가까운 값으로 변환

### MinMaxScaler
* 데이터 값을 `0`과 `1`사이의 범위 값으로 변환(음수값이 있으면 `-1`에서 `1`값으로 변환)
* 데이터의 분포가 가우시안 분포가 아닐 경우에,Min, Max Scale을 적용해 볼 수 있다.

In [15]:
from sklearn.preprocessing import MinMaxScaler

# MinMaxScaler객체 생성
scaler = MinMaxScaler()

#MinMaxScaler()로 데이터 세트 변환, fit(), transform()호출
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

In [18]:
#transform() 시 스케일변환된 데이터 세트가 numpy.ndarray()로 반환돼 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data = iris_scaled, columns = iris.feature_names)
print('feature들의 최솟값')
print(iris_df_scaled.min())
print('feature들의 최댓값')
print(iris_df_scaled.max())

feature들의 최솟값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
feature들의 최댓값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


* 모든 피처에서 `0`과 `1`사이의 값으로 변환되는 스케일링이 적용

## 학습 데이터와 테스트  데이터의 스케일링 변환 시 유의점

In [19]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

# 학습 데이터는 0부터 10까지 , 테스트 데이터는 0부터 5까지 값을 가지는 데이터 세트로 생성
# Scaler클래스의 fist(), transform()은 2차원 이상 데이터만 가능하므로 reshape(-1, 1)로 차원 변경
train_array = np.arange(0, 11).reshape(-1, 1)
test_array = np.arange(0,6).reshape(-1, 1)

In [21]:
# MinMaxScaler객체에 별도의 feature_range 파라미터 값을 지정하지 않으면 0 ~ 1값으로 변환
scaler = MinMaxScaler()

# fit()하게 되면 train_array 데이터의 최솟값이 0, 최댓값이 10으로 설정
scaler.fit(train_array)

# 1 / 10 scale로 train_array 데이터 변환함, 원본 10 -> 1 로 변환됨.
train_scaled = scaler.transform(train_array)

print('원본 train_array 데이터 : ', np.round(train_array.reshape(-1), 2))
print('scaled된 train_array 데이터 : ', np.round(train_scaled.reshape(-1), 2))

원본 train_array 데이터 :  [ 0  1  2  3  4  5  6  7  8  9 10]
scaled된 train_array 데이터 :  [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


#### 테스트 데이터세트를 변환하는데 ,fit()을 호출해 스케일링 기준 정보를 다시 적용한뒤 transform()를 수행해 보면...

In [24]:
# MinMaxScaler에 test_array를 fit()하게 되면 원본 데이터의 최솟값이 0, 최댓값이 5로 설정됨
scaler.fit(test_array)

# 1 / 5 scale로 test_array데이터 변환함, 원본 5 -> 1로 변환.
test_scaled = scaler.transform(test_array)

# test_array의 scale변환 출력.
print('원본 test_array 데이터 :', np.round(test_array.reshape(-1),2))
print('scaled된 test_array 데이터 :', np.round(test_scaled.reshape(-1),2))

원본 test_array 데이터 : [0 1 2 3 4 5]
scaled된 test_array 데이터 : [0.  0.2 0.4 0.6 0.8 1. ]


#### 테스트 데이터세트를 변환하는데 ,fit()을 호출하지 않고 학습데이터로 fit()한 후 , 수행한 MinMaxScaler의 객체를 이용해 transform()

In [26]:
scaler = MinMaxScaler()
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)
print('원본 train_array 데이터 :', np.round(train_array.reshape(-1),2))
print('scaled된 train_array 데이터 :', np.round(train_scaled.reshape(-1),2))

# test_array에 scale변환을 할때 반드시 fit()을 호출하지 않고 transform()만으로 변환해야 함.
test_scaled = scaler.transform(test_array)
print('\n원본 test_array 데이터 :', np.round(test_array.reshape(-1),2))
print('scaled된 test_array 데이터 :', np.round(test_scaled.reshape(-1),2))

원본 train_array 데이터 : [ 0  1  2  3  4  5  6  7  8  9 10]
scaled된 train_array 데이터 : [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

원본 test_array 데이터 : [0 1 2 3 4 5]
scaled된 test_array 데이터 : [0.  0.1 0.2 0.3 0.4 0.5]


* 보는 바와 같이 학습된 스케일링 기준이 적용됨을 확인.(1 / 10)

## 학습데이터와 테스트 데이터의 `fit()`, `transform()`,`fit_transform()` 스케일링시 유의점.

* 1) 가능하다면 전체 데이터의 스케일링 변환을 적용한 뒤 학습과 테스트 데이터로 분리
* 2) 1)이 여의치 않다면 테스트 데이터 변환 시에는 `fit()`이나 `transform()`을 적용하지 않고 학습 데이터로 이미 `fit()`된 Scaler객체를 이용해 `transform()`으로 변환