# 데이터 전처리(Preprocessing)
* 데이터클랜징
* 결손값 처리(Null/NaN)처리
* 데이터 인코딩(레이블, 원-핫 인코딩)
* 데이터 스케일링
* 이상치 제거 
* Feature선택 , 추출 및 가공

## 데이터 인코딩

머신러닝 알고리즘은 문자열 데이터 속성을 입력받지 않으며 모든 데이터는 숫자형으로 표현되어야 합니다.

문자형 카테고리형 속성은 모두 숫자값으로 변환/인코딩되어야 합니다.

* Label encoding : 카테고리형 피처를 코드형 숫자값으로 변환
* One Hot Encoding : 피처값의 유형에 따라 새로운 피처를 추가해 고유 값에 해당하는 칼럼에만 `1`을 포함하고 나머지 컬럼에는 `0`을 표시

### 레이블 인코딩
* LabelEncoder클래스로 구현 : `fit()`과 `transform()`

In [2]:
from sklearn.preprocessing import LabelEncoder

In [6]:
items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

# LabelEncoder객체를 생성 후 fit()과 transform()으로 레이블 인코딩
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print("인코딩 변환 값 : ", labels)

인코딩 변환 값 :  [0 1 4 5 3 3 2 2]


In [8]:
print('인코딩 클래스 : ', encoder.classes_)

인코딩 클래스 :  ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [9]:
print('디코딩 원본값 : ', encoder.inverse_transform(labels))

디코딩 원본값 :  ['TV' '냉장고' '전자레인지' '컴퓨터' '선풍기' '선풍기' '믹서' '믹서']


### 원-핫 인코딩(One-Hot Encoding)
- 원-핫 인코딩은 피처 값의 유형에 따라 새로운 피처를 추가해 고유 값에 해당하는 컬럼에만 1을 표시하고 나머지 컬럼에는 0을 표시하는 방식
- 컬럼 값의 Distinct한 갯수만큼 신규 피처가 추가됨

In [12]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [14]:
items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

# 먼저 숫자값으로 변환을 위해 LabelEncoder로 변환합니다.- 스스로 변환시키지 못하기때문에 먼저 LabelEncoder를 해야함.
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

# 1차원 데이터를 2차원 데이터로 변환합니다.
labels = labels.reshape(-1, 1)  # 열을 무조건 1로 고정하고 행은 맟춰서 변경됨
display(labels)

array([[0],
       [1],
       [4],
       [5],
       [3],
       [3],
       [2],
       [2]], dtype=int64)

In [15]:
# 원-핫 인코딩
oh_encode = OneHotEncoder()
oh_encode.fit(labels)
oh_labels = oh_encode.transform(labels)

print('One-Hot Encoding ')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

One-Hot Encoding 
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


#### `get_dummies(DataFrame)`를 이용한 원-핫 인코딩 

In [16]:
import pandas as pd

In [18]:
df = pd.get_dummies(items)
display(items, df)

['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

TV  냉장고  믹서  선풍기  전자레인지  컴퓨터
0   1    0   0    0      0    0
1   0    1   0    0      0    0
2   0    0   0    0      1    0
3   0    0   0    0      0    1
4   0    0   0    1      0    0
5   0    0   0    1      0    0
6   0    0   1    0      0    0
7   0    0   1    0      0    0

## 피처 스케일링과 정규화
서로 다른 변수의 값의 범위를 일정한 수준으로 맞추는 작업을 말함.
* 표준화 : 데이터의 피처 각각이 평균이 `0`이고 분산이 `1`인 가우시안 정규분포를 가진값으로 변환
* 정규화 : 서로 다른 피처의 크기를 통일하기 위해 크기를 변환해주는 개념.즉, 개별 데이터의 크기를 모두 똑같은 단위로 변경하는것.

### StandardScaler
* 개별 피처를 평균이 `0`이고, 분산이 `1`인 값으로 변환(가우시안 정규분포)

In [21]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
import pandas as pd

In [20]:
# 붓꽃 데이터 세트를 로딩하고 DataFrame으로 변환합니다.
iris = load_iris()
iris_df = pd.DataFrame(data = iris.data, columns = iris.feature_names)

print('feature들의 평균값')
print(iris_df.mean())

print('\nfeature들의 분산 값')
print(iris_df.std())

feature들의 평균값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

feature들의 분산 값
sepal length (cm)    0.828066
sepal width (cm)     0.435866
petal length (cm)    1.765298
petal width (cm)     0.762238
dtype: float64


* 수행

In [25]:
scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

print(type(iris_scaled))  # <class 'numpy.ndarray'>
display(iris_scaled)

<class 'numpy.ndarray'>


array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [26]:
#transform() 시 스케일변환된 데이터 세트가 numpy.ndarray()로 반환돼 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data = iris_scaled, columns = iris.feature_names)
print('feature들의 평균값')
display(iris_df_scaled.mean())
print('\nfeature들의 분산값')
display(iris_df_scaled.var())

feature들의 평균값


sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64


feature들의 분산값


sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64

* 모든 컬럼 값의 평균이 0에 아주 가까운 값으로 , 그리고 분산은 1에 아주 가까운 값으로 변환

### MinMaxScaler
* 데이터 값을 `0`과 `1`사이의 범위 값으로 변환(음수값이 있으면 `-1`에서 `1`값으로 변환)
* 데이터의 분포가 가우시안 분포가 아닐 경우에,Min, Max Scale을 적용해 볼 수 있다.

In [27]:
from sklearn.preprocessing import MinMaxScaler

In [30]:
scaler = MinMaxScaler()

scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)

display(type(iris_scaled), iris_scaled)

numpy.ndarray

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [31]:
#transform() 시 스케일변환된 데이터 세트가 numpy.ndarray()로 반환돼 이를 DataFrame으로 변환
iris_df_scaled = pd.DataFrame(data = iris_scaled, columns = iris.feature_names)
print('feature들의 최솟값')
display(iris_df_scaled.min())
print('feature들의 최댓값')
display(iris_df_scaled.max())

feature들의 최솟값


sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

feature들의 최댓값


sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64

* 모든 피처에서 `0`과 `1`사이의 값으로 변환되는 스케일링이 적용

## 학습 데이터와 테스트  데이터의 스케일링 변환 시 유의점

In [35]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

# 1.학습 데이터는 0부터 10까지 , 테스트 데이터는 0부터 5까지 값을 가지는 데이터 세트로 생성
# 2.Scaler클래스의 fist(), transform()은 2차원 이상 데이터만 가능하므로 reshape(-1, 1)로 차원 변경
train_array = np.arange(0, 10).reshape(-1, 1)
test_array  = np.arange(0, 5).reshape(-1, 1)

display(train_array, test_array)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [37]:
# MinMaxScaler객체에 별도의 feature_range 파라미터 값을 지정하지 않으면 0 ~ 1값으로 변환
scaler = MinMaxScaler()
# fit()하게 되면 train_array 데이터의 최솟값이 0, 최댓값이 10으로 설정
scaler.fit(train_array)
# 1 / 10 scale로 train_array 데이터 변환함, 원본 10 -> 1 로 변환됨.
train_scaled = scaler.transform(train_array)
print('원본 train_array 데이터 : ', np.round(train_array.reshape(-1), 2))
print('scaled된 train_array 데이터 : ', np.round(train_scaled.reshape(-1), 2))

원본 train_array 데이터 :  [0 1 2 3 4 5 6 7 8 9]
scaled된 train_array 데이터 :  [0.   0.11 0.22 0.33 0.44 0.56 0.67 0.78 0.89 1.  ]


#### 테스트 데이터세트를 변환하는데 ,fit()을 호출해 스케일링 기준 정보를 다시 적용한뒤 transform()를 수행해 보면...

In [38]:
# MinMaxScaler에 test_array를 fit()하게 되면 원본 데이터의 최솟값이 0, 최댓값이 5로 설정됨
scaler.fit(test_array)
# 1 / 5 scale로 test_array데이터 변환함, 원본 5 -> 1로 변환.
test_scaled = scaler.transform(test_array)
# test_array의 scale변환 출력.
print('원본 test_array 데이터 :', np.round(test_array.reshape(-1),2))
print('scaled된 test_array 데이터 :', np.round(test_scaled.reshape(-1),2))

원본 test_array 데이터 : [0 1 2 3 4]
scaled된 test_array 데이터 : [0.   0.25 0.5  0.75 1.  ]


테스트 데이터세트를 변환하는데 ,fit()을 호출하지 않고 학습데이터로 fit()한 후 , 수행한 MinMaxScaler의 객체를 이용해 transform()

In [39]:
scaler = MinMaxScaler()
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)
print('원본 train_array 데이터 :', np.round(train_array.reshape(-1),2))
print('scaled된 train_array 데이터 :', np.round(train_scaled.reshape(-1),2))

# test_array에 scale변환을 할때 반드시 fit()을 호출하지 않고 transform()만으로 변환해야 함.
test_scaled = scaler.transform(test_array)
print('\n원본 test_array 데이터 :', np.round(test_array.reshape(-1),2))
print('scaled된 test_array 데이터 :', np.round(test_scaled.reshape(-1),2))

원본 train_array 데이터 : [0 1 2 3 4 5 6 7 8 9]
scaled된 train_array 데이터 : [0.   0.11 0.22 0.33 0.44 0.56 0.67 0.78 0.89 1.  ]

원본 test_array 데이터 : [0 1 2 3 4]
scaled된 test_array 데이터 : [0.   0.11 0.22 0.33 0.44]


* 보는 바와 같이 학습된 스케일링 기준이 적용됨을 확인.(1 / 10)

## 학습데이터와 테스트 데이터의 `fit()`, `transform()`,`fit_transform()` 스케일링시 유의점.

* 1) 가능하다면 전체 데이터의 스케일링 변환을 적용한 뒤 학습과 테스트 데이터로 분리
* 2) 1)이 여의치 않다면 테스트 데이터 변환 시에는 `fit()`이나 `transform()`을 적용하지 않고 학습 데이터로 이미 `fit()`된 Scaler객체를 이용해 `transform()`으로 변환